/**
 * 房东租约管理状态管理
 */

import { defineStore } from 'pinia';
import { ref, computed } from 'vue';
import {
  getLandlordLeaseList,
  getLandlordLeaseDetail,
  getLandlordLeaseStatistics,
  getLandlordLeaseStatusStats,
  getLandlordLeaseSourceStats,
  getExpiringLeases,
  updateLeaseStatus,
  createLease,
  updateLease,
  sendExpirationReminder,
  LeaseStatus,
  LeaseSourceType,
  type LandlordLeaseVo,
  type LandlordLeaseDetailVo,
  type LandlordLeaseStatisticsVo,
  type StatusStatVo,
  type SourceStatVo,
  type LandlordLeaseQueryVo,
  type LandlordLeaseCreateVo,
  type PageResult
} from '@/api/landlord/lease';

export const useLandlordLeaseStore = defineStore('landlordLease', () => {
  // 状态数据
  const loading = ref(false);
  const refreshing = ref(false);
  const submitting = ref(false);
  
  // 租约列表相关
  const leaseList = ref<LandlordLeaseVo[]>([]);
  const listLoading = ref(false);
  const listFinished = ref(false);
  const currentPage = ref(1);
  const pageSize = ref(10);
  const totalCount = ref(0);
  const queryParams = ref<LandlordLeaseQueryVo>({});
  
  // 租约详情
  const currentLease = ref<LandlordLeaseDetailVo | null>(null);
  const leaseDetailLoading = ref(false);
  
  // 统计数据
  const statistics = ref<LandlordLeaseStatisticsVo>({
    total: 0,
    signing: 0,
    signed: 0,
    canceled: 0,
    expired: 0,
    withdrawing: 0,
    withdrawn: 0,
    renewing: 0,
    expiring: 0,
    totalRent: 0,
    totalDeposit: 0,
    newLease: 0,
    renewLease: 0,
    directApplication: 0,
    autoGenerated: 0,
    manualCreated: 0
  });
  
  const statusStats = ref<StatusStatVo[]>([]);
  const sourceStats = ref<SourceStatVo[]>([]);
  const statisticsLoading = ref(false);
  
  // 即将到期租约
  const expiringLeases = ref<LandlordLeaseVo[]>([]);
  const expiringLoading = ref(false);
  
  // 缓存管理
  const cacheExpiry = ref<Record<string, number>>({});
  const CACHE_DURATION = 5 * 60 * 1000; // 5分钟缓存
  
  // 计算属性
  const hasMoreLeases = computed(() => {
    return leaseList.value.length < totalCount.value;
  });
  
  const urgentExpiringCount = computed(() => {
    return expiringLeases.value.filter(lease => lease.remainingDays <= 7).length;
  });
  
  const isStatisticsCacheValid = computed(() => {
    const cacheTime = cacheExpiry.value.statistics;
    return cacheTime && Date.now() - cacheTime < CACHE_DURATION;
  });
  
  // Actions
  
  /**
   * 加载租约列表
   */
  const loadLeaseList = async (refresh = false) => {
    try {
      if (refresh) {
        currentPage.value = 1;
        listFinished.value = false;
        refreshing.value = true;
      } else {
        listLoading.value = true;
      }
      
      const response = await getLandlordLeaseList(
        currentPage.value,
        pageSize.value,
        queryParams.value
      );
      
      const { records, total } = response.data;
      
      if (refresh) {
        leaseList.value = records;
      } else {
        leaseList.value.push(...records);
      }
      
      totalCount.value = total;
      currentPage.value++;
      
      if (leaseList.value.length >= total) {
        listFinished.value = true;
      }
      
      return response.data;
    } catch (error) {
      console.error('加载租约列表失败:', error);
      throw error;
    } finally {
      listLoading.value = false;
      refreshing.value = false;
    }
  };
  
  /**
   * 搜索租约
   */
  const searchLeases = async (keyword: string) => {
    queryParams.value.keyword = keyword;
    return await loadLeaseList(true);
  };
  
  /**
   * 筛选租约
   */
  const filterLeases = async (filters: Partial<LandlordLeaseQueryVo>) => {
    Object.assign(queryParams.value, filters);
    return await loadLeaseList(true);
  };
  
  /**
   * 清除筛选条件
   */
  const clearFilters = async () => {
    queryParams.value = {};
    return await loadLeaseList(true);
  };
  
  /**
   * 加载租约详情
   */
  const loadLeaseDetail = async (leaseId: number, forceRefresh = false) => {
    try {
      // 检查缓存
      const cacheKey = `lease_${leaseId}`;
      const cacheTime = cacheExpiry.value[cacheKey];
      
      if (!forceRefresh && currentLease.value?.id === leaseId && 
          cacheTime && Date.now() - cacheTime < CACHE_DURATION) {
        return currentLease.value;
      }
      
      leaseDetailLoading.value = true;
      const response = await getLandlordLeaseDetail(leaseId);
      
      currentLease.value = response.data;
      cacheExpiry.value[cacheKey] = Date.now();
      
      return response.data;
    } catch (error) {
      console.error('加载租约详情失败:', error);
      throw error;
    } finally {
      leaseDetailLoading.value = false;
    }
  };
  
  /**
   * 加载统计数据
   */
  const loadStatistics = async (forceRefresh = false) => {
    try {
      if (!forceRefresh && isStatisticsCacheValid.value) {
        return {
          statistics: statistics.value,
          statusStats: statusStats.value,
          sourceStats: sourceStats.value
        };
      }
      
      statisticsLoading.value = true;
      
      const [statisticsRes, statusStatsRes, sourceStatsRes] = await Promise.all([
        getLandlordLeaseStatistics(),
        getLandlordLeaseStatusStats(),
        getLandlordLeaseSourceStats()
      ]);
      
      statistics.value = statisticsRes.data;
      statusStats.value = statusStatsRes.data;
      sourceStats.value = sourceStatsRes.data;
      
      cacheExpiry.value.statistics = Date.now();
      
      return {
        statistics: statistics.value,
        statusStats: statusStats.value,
        sourceStats: sourceStats.value
      };
    } catch (error) {
      console.error('加载统计数据失败:', error);
      throw error;
    } finally {
      statisticsLoading.value = false;
    }
  };
  
  /**
   * 加载即将到期租约
   */
  const loadExpiringLeases = async (days = 30) => {
    try {
      expiringLoading.value = true;
      const response = await getExpiringLeases(days);
      
      expiringLeases.value = response.data.sort((a, b) => a.remainingDays - b.remainingDays);
      
      return response.data;
    } catch (error) {
      console.error('加载即将到期租约失败:', error);
      throw error;
    } finally {
      expiringLoading.value = false;
    }
  };
  
  /**
   * 更新租约状态
   */
  const changeLeaseStatus = async (leaseId: number, status: LeaseStatus) => {
    try {
      loading.value = true;
      await updateLeaseStatus(leaseId, status);
      
      // 更新本地状态
      if (currentLease.value?.id === leaseId) {
        currentLease.value.status = status;
      }
      
      // 更新列表中的状态
      const leaseIndex = leaseList.value.findIndex(lease => lease.id === leaseId);
      if (leaseIndex !== -1) {
        leaseList.value[leaseIndex].status = status;
      }
      
      // 清除统计缓存
      delete cacheExpiry.value.statistics;
      
      return true;
    } catch (error) {
      console.error('更新租约状态失败:', error);
      throw error;
    } finally {
      loading.value = false;
    }
  };
  
  /**
   * 创建租约
   */
  const createNewLease = async (data: LandlordLeaseCreateVo) => {
    try {
      submitting.value = true;
      const response = await createLease(data);
      
      // 清除缓存，重新加载数据
      await Promise.all([
        loadLeaseList(true),
        loadStatistics(true)
      ]);
      
      return response.data;
    } catch (error) {
      console.error('创建租约失败:', error);
      throw error;
    } finally {
      submitting.value = false;
    }
  };
  
  /**
   * 更新租约
   */
  const updateExistingLease = async (leaseId: number, data: Partial<LandlordLeaseCreateVo>) => {
    try {
      submitting.value = true;
      const response = await updateLease(leaseId, data);
      
      // 清除相关缓存
      delete cacheExpiry.value[`lease_${leaseId}`];
      delete cacheExpiry.value.statistics;
      
      // 重新加载详情
      if (currentLease.value?.id === leaseId) {
        await loadLeaseDetail(leaseId, true);
      }
      
      return response.data;
    } catch (error) {
      console.error('更新租约失败:', error);
      throw error;
    } finally {
      submitting.value = false;
    }
  };
  
  /**
   * 发送到期提醒
   */
  const sendReminder = async (leaseId: number) => {
    try {
      loading.value = true;
      await sendExpirationReminder(leaseId);
      return true;
    } catch (error) {
      console.error('发送提醒失败:', error);
      throw error;
    } finally {
      loading.value = false;
    }
  };
  
  /**
   * 批量发送提醒
   */
  const batchSendReminders = async (leaseIds: number[]) => {
    try {
      loading.value = true;
      
      const promises = leaseIds.map(id => 
        sendExpirationReminder(id).catch(error => {
          console.error(`发送提醒失败 (租约ID: ${id}):`, error);
          return null;
        })
      );
      
      const results = await Promise.allSettled(promises);
      const successCount = results.filter(result => result.status === 'fulfilled').length;
      
      return { successCount, totalCount: leaseIds.length };
    } catch (error) {
      console.error('批量发送提醒失败:', error);
      throw error;
    } finally {
      loading.value = false;
    }
  };
  
  /**
   * 重置状态
   */
  const resetState = () => {
    leaseList.value = [];
    currentLease.value = null;
    queryParams.value = {};
    currentPage.value = 1;
    listFinished.value = false;
    totalCount.value = 0;
    cacheExpiry.value = {};
  };
  
  /**
   * 清除缓存
   */
  const clearCache = () => {
    cacheExpiry.value = {};
  };
  
  return {
    // 状态
    loading,
    refreshing,
    submitting,
    listLoading,
    listFinished,
    leaseDetailLoading,
    statisticsLoading,
    expiringLoading,
    
    // 数据
    leaseList,
    currentLease,
    statistics,
    statusStats,
    sourceStats,
    expiringLeases,
    queryParams,
    currentPage,
    pageSize,
    totalCount,
    
    // 计算属性
    hasMoreLeases,
    urgentExpiringCount,
    isStatisticsCacheValid,
    
    // 方法
    loadLeaseList,
    searchLeases,
    filterLeases,
    clearFilters,
    loadLeaseDetail,
    loadStatistics,
    loadExpiringLeases,
    changeLeaseStatus,
    createNewLease,
    updateExistingLease,
    sendReminder,
    batchSendReminders,
    resetState,
    clearCache
  };
});

export type LandlordLeaseStore = ReturnType<typeof useLandlordLeaseStore>;