package com.atguigu.lease.web.app.vo.lease;

import com.atguigu.lease.model.entity.ApartmentInfo;
import com.atguigu.lease.model.entity.LeaseTerm;
import com.atguigu.lease.model.entity.PaymentType;
import com.atguigu.lease.model.entity.RoomInfo;
import com.atguigu.lease.model.enums.LeaseSourceType;
import com.atguigu.lease.model.enums.LeaseStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 租约详情VO
 */
@Data
@Schema(description = "租约详情")
public class LeaseAgreementVo {

    @Schema(description = "租约ID")
    private Long id;

    @Schema(description = "承租人手机号码")
    private String phone;

    @Schema(description = "承租人姓名")
    private String name;

    @Schema(description = "承租人身份证号码")
    private String identificationNumber;

    @Schema(description = "租约开始日期")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date leaseStartDate;

    @Schema(description = "租约结束日期")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date leaseEndDate;

    @Schema(description = "租金（元/月）")
    private BigDecimal rent;

    @Schema(description = "押金（元）")
    private BigDecimal deposit;

    @Schema(description = "租约状态")
    private LeaseStatus status;

    @Schema(description = "租约来源")
    private LeaseSourceType sourceType;

    @Schema(description = "创建者类型：1-官方，2-房东")
    private Integer creatorType;

    @Schema(description = "是否自动生成：0-否，1-是")
    private Integer autoGenerated;

    @Schema(description = "创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @Schema(description = "公寓信息")
    private ApartmentInfo apartmentInfo;

    @Schema(description = "房间信息")
    private RoomInfo roomInfo;

    @Schema(description = "支付方式")
    private PaymentType paymentType;

    @Schema(description = "租期信息")
    private LeaseTerm leaseTerm;

    @Schema(description = "备注信息")
    private String additionalInfo;
}