package com.atguigu.lease.web.admin.mapper;

import com.atguigu.lease.model.entity.LeaseAgreement;
import com.atguigu.lease.web.admin.vo.agreement.AgreementQueryVo;
import com.atguigu.lease.web.admin.vo.agreement.AgreementVo;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
* @author liubo
* @description 针对表【lease_agreement(租约信息表)】的数据库操作Mapper
* @createDate 2023-07-24 15:48:00
* @Entity com.atguigu.lease.model.LeaseAgreement
*/
public interface LeaseAgreementMapper extends BaseMapper<LeaseAgreement> {

    IPage<AgreementVo> pageAgreementByQuery(Page<AgreementVo> page, AgreementQueryVo queryVo);

    /**
     * 获取所有租约列表（官方后台统一查看）
     * 支持按创建者类型、来源类型筛选，显示官方和房东生成的所有合同
     */
    IPage<AgreementVo> getAllLeases(Page<AgreementVo> page, AgreementQueryVo queryVo);

    /**
     * 根据创建者类型查询租约列表
     */
    List<LeaseAgreement> selectByCreatorType(@Param("creatorType") Integer creatorType);

    /**
     * 根据创建者ID查询租约列表
     */
    List<LeaseAgreement> selectByCreatorId(@Param("creatorId") Long creatorId);

    /**
     * 根据来源类型查询租约列表
     */
    List<LeaseAgreement> selectBySourceType(@Param("sourceType") Integer sourceType);

    /**
     * 根据申请ID查询租约
     */
    LeaseAgreement selectByApplicationId(@Param("applicationId") Long applicationId);

    /**
     * 查询自动生成的租约列表
     */
    List<LeaseAgreement> selectAutoGenerated();

    /**
     * 统计租约数量按创建者类型分组
     */
    List<Object> selectLeaseStatisticsByCreatorType();
}




