<template>
  <div>
    <!-- 统计卡片 -->
    <el-row :gutter="20" style="margin-bottom: 20px">
      <el-col :span="6">
        <el-card class="statistics-card">
          <div class="card-content">
            <div class="card-icon total">
              <el-icon><Document /></el-icon>
            </div>
            <div class="card-info">
              <div class="card-title">租约总数</div>
              <div class="card-value">{{ statistics.totalCount }}</div>
            </div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="statistics-card">
          <div class="card-content">
            <div class="card-icon signed">
              <el-icon><Check /></el-icon>
            </div>
            <div class="card-info">
              <div class="card-title">已签约</div>
              <div class="card-value">{{ getStatusCount(AgreementStatus.SIGNED) }}</div>
            </div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="statistics-card">
          <div class="card-content">
            <div class="card-icon waiting">
              <el-icon><Clock /></el-icon>
            </div>
            <div class="card-info">
              <div class="card-title">待确认</div>
              <div class="card-value">{{ getStatusCount(AgreementStatus.WAITING) }}</div>
            </div>
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="statistics-card">
          <div class="card-content">
            <div class="card-icon auto">
              <el-icon><Star /></el-icon>
            </div>
            <div class="card-info">
              <div class="card-title">自动生成</div>
              <div class="card-value">{{ autoGeneratedCount }}</div>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 图表区域 -->
    <el-row :gutter="20" style="margin-bottom: 20px">
      <el-col :span="12">
        <el-card>
          <template #header>
            <span>租约状态分布</span>
          </template>
          <div ref="statusChartRef" style="height: 300px"></div>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card>
          <template #header>
            <span>租约来源分布</span>
          </template>
          <div ref="sourceChartRef" style="height: 300px"></div>
        </el-card>
      </el-col>
    </el-row>

    <el-card>
      <ProTable
        ref="proTable"
        :dataCallback="dataCallback"
        :columns="columns"
        :requestApi="getAgreementInfoList"
        :initParam="initParam"
        :stripe="true"
      >
        <template #tableHeader>
          <el-button type="primary" icon="Plus" @click="addHandle">
            新增租约
          </el-button>
          <el-button type="success" icon="Refresh" @click="refreshStatistics">
            刷新统计
          </el-button>
          <el-button type="warning" icon="Clock" @click="viewExpiringLeases">
            即将到期
          </el-button>
          <el-button type="info" icon="View" @click="switchToAllView">
            {{ showAllLeases ? '显示普通视图' : '显示所有租约' }}
          </el-button>
        </template>
        <!-- 表格操作 -->
        <template #operation="scope">
          <el-button type="success" icon="Edit" size="small" @click="editHandle(scope.row)">
            修改
          </el-button>
          <el-button type="danger" icon="Delete" size="small" @click="deleteHandle(scope.row)">
            删除
          </el-button>
          
          <!-- 状态相关操作 -->
          <el-button
            type="success"
            icon="Check"
            size="small"
            v-if="scope.row.status === AgreementStatus.RENEW_TO_BE_CONFIRMED"
            @click="confirmLeaseHandle(scope.row)"
          >
            同意续约
          </el-button>
          <el-button
            type="danger"
            icon="Close"
            size="small"
            v-if="scope.row.status === AgreementStatus.RENEW_TO_BE_CONFIRMED"
            @click="rejectLeaseHandle(scope.row)"
          >
            拒绝续约
          </el-button>
          <el-button
            type="warning"
            icon="Warning"
            size="small"
            v-if="scope.row.status === AgreementStatus.WAITING"
            @click="cancelLeaseHandle(scope.row)"
          >
            取消租约
          </el-button>
          <el-button
            type="danger"
            icon="Warning"
            size="small"
            v-if="scope.row.status === AgreementStatus.TO_BE_CONFIRMED"
            @click="confirmThrowLeaseHandle(scope.row)"
          >
            确认退租
          </el-button>
          
          <!-- 新增功能按钮 -->
          <el-button
            type="info"
            icon="Bell"
            size="small"
            @click="sendReminderHandle(scope.row)"
            title="发送到期提醒"
          >
            提醒
          </el-button>
          <el-button
            type="primary"
            icon="Refresh"
            size="small"
            @click="updateAndResendHandle(scope.row)"
            title="修改并重新发送"
          >
            重发
          </el-button>
          <el-button
            type="danger"
            icon="Close"
            size="small"
            v-if="scope.row.status === AgreementStatus.SIGNED"
            @click="terminateLeaseHandle(scope.row)"
            title="终止租约（退租）"
          >
            终止
          </el-button>
        </template>
      </ProTable>
    </el-card>
  </div>
</template>

<script setup lang="tsx">
import { onMounted, reactive, ref, computed, nextTick } from 'vue'
import type { ColumnProps } from '@/components/ProTable/src/types'
import ProTable from '@/components/ProTable/src/ProTable.vue'
import { useRouter } from 'vue-router'
import { useHandleData } from '@/hooks/useHandleData'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as echarts from 'echarts'
import { Document, Check, Clock, Star } from '@element-plus/icons-vue'
import {
  getApartmentListByDistrictId,
  getCityList,
  getDistrictList,
  getProvinceList,
} from '@/api/apartmentManagement'
import {
  ApartmentInterface,
  RegionInterface,
} from '@/api/apartmentManagement/types'
import {
  AgreementSourceMap,
  AgreementStatus,
  AgreementStatusMap,
  CreatorType,
  CreatorTypeMap,
  getLabelByValue,
} from '@/enums/constEnums'
import {
  deleteAgreementInfoById,
  getAgreementInfoList,
  getAllAgreements,
  updateAgreementStatusById,
  getAgreementStatistics,
  updateLeaseStatus,
  batchUpdateLeaseStatus,
  getExpiringLeases,
  terminateLease,
  sendExpirationReminder,
  updateAndResendLease,
} from '@/api/rentManagement'
import { AgreementInfoInterface } from '@/api/rentManagement/types'
const router = useRouter()

// *获取 ProTable 元素，调用其获取刷新数据方法
const proTable = ref<InstanceType<typeof ProTable>>()

// 视图切换状态
const showAllLeases = ref(false)

// 统计数据
const statistics = reactive({
  totalCount: 0,
  signed: 0,
  signing: 0,
  canceled: 0,
  official: 0,
  landlord: 0,
  newLease: 0,
  renewLease: 0,
  directApplication: 0,
  autoGenerated: 0,
  statusStats: [] as { status: number; count: number; label: string }[],
  sourceStats: [] as { sourceType: number; count: number; label: string }[],
  creatorStats: [] as { creatorType: number; count: number; label: string }[],
  monthlyStats: [] as { month: string; count: number }[],
})

// 图表引用
const statusChartRef = ref<HTMLDivElement>()
const sourceChartRef = ref<HTMLDivElement>()
let statusChart: echarts.ECharts | null = null
let sourceChart: echarts.ECharts | null = null
// 地区数据
const areaInfo = reactive({
  // 省份数据
  provinceList: [] as RegionInterface[],
  provinceId: '',
  // 市区数据
  cityList: [] as RegionInterface[],
  cityId: '',
  // 区县数据
  districtList: [] as RegionInterface[],
  districtId: '',
  // 公寓数据
  apartmentList: [] as ApartmentInterface[],
  apartmentId: '',
})
// *表格配置项
const columns: ColumnProps[] = [
  {
    prop: 'name',
    label: '姓名',
    search: { el: 'input', props: { placeholder: '请输入姓名' } },
  },
  {
    prop: 'phone',
    label: '手机',
    search: { el: 'input', props: { placeholder: '请输入手机号' } },
  },
  {
    prop: 'roomNumber',
    label: '房间',
    search: { el: 'input', props: { placeholder: '请输入房间号' } },
    render: ({ row }: { row: AgreementInfoInterface }) => {
      return row.roomInfo.roomNumber
    },
  },
  {
    prop: 'provinceId',
    label: '省份',
    isShow: false,
    fieldNames: { label: 'name', value: 'id' },
    search: {
      el: 'select',
      render: () => {
        return (
          <el-select
            v-model={areaInfo.provinceId}
            placeholder="请选择省份"
            clearable
            key="provinceId"
            onChange={provinceChangeCallback}
            onClear={provinceClearCallback}
          >
            {areaInfo.provinceList.map((item) => (
              <el-option
                key={item.id}
                label={item.name}
                value={item.id}
              ></el-option>
            ))}
          </el-select>
        )
      },
    },
  },
  {
    prop: 'cityId',
    label: '城市',
    isShow: false,
    fieldNames: { label: 'name', value: 'id' },
    search: {
      el: 'select',
      key: 'cityId',
      render: () => {
        return (
          <el-select
            v-model={areaInfo.cityId}
            placeholder="请选择城市"
            clearable
            key="cityId"
            onChange={cityChangeCallback}
            onClear={cityClearCallback}
          >
            {areaInfo.cityList.map((item) => (
              <el-option
                key={item.id}
                label={item.name}
                value={item.id}
              ></el-option>
            ))}
          </el-select>
        )
      },
    },
  },
  {
    prop: 'districtId',
    label: '区域',
    isShow: false,
    fieldNames: { label: 'name', value: 'id' },
    search: {
      el: 'select',
      key: 'districtId',
      render: () => {
        return (
          <el-select
            v-model={areaInfo.districtId}
            placeholder="请选择区域"
            clearable
            onChange={districtChangeCallback}
            onClear={districtClearCallback}
          >
            {areaInfo.districtList.map((item) => (
              <el-option
                key={item.id}
                label={item.name}
                value={item.id}
              ></el-option>
            ))}
          </el-select>
        )
      },
    },
  },
  {
    prop: 'apartmentId',
    label: '公寓',
    isShow: false,
    fieldNames: { label: 'name', value: 'id' },
    search: {
      el: 'select',
      key: 'apartmentId',
      render: () => {
        return (
          <el-select
            v-model={areaInfo.apartmentId}
            placeholder="请选择公寓"
            clearable
            onChange={apartmentChangeCallback}
            onClear={apartmentClearCallback}
          >
            {areaInfo.apartmentList.map((item) => (
              <el-option
                key={item.id}
                label={item.name}
                value={item.id}
              ></el-option>
            ))}
          </el-select>
        )
      },
    },
  },
  {
    prop: 'sourceType',
    label: '租约来源',
    isShow: false,
    search: {
      el: 'select',
      props: { placeholder: '请选择租约来源', clearable: true },
    },
    enum: [
      { label: '新签', value: 1 },
      { label: '续约', value: 2 },
      { label: '直接入住申请', value: 3 },
    ],
  },
  {
    prop: 'creatorType',
    label: '创建者类型',
    isShow: false,
    search: {
      el: 'select',
      props: { placeholder: '请选择创建者类型', clearable: true },
    },
    enum: [
      { label: '官方', value: 1 },
      { label: '房东', value: 2 },
    ],
  },
  {
    prop: 'autoGenerated',
    label: '生成方式',
    isShow: false,
    search: {
      el: 'select',
      props: { placeholder: '请选择生成方式', clearable: true },
    },
    enum: [
      { label: '手动创建', value: 0 },
      { label: '自动生成', value: 1 },
    ],
  },
  {
    prop: 'status',
    label: '租约状态',
    isShow: false,
    search: {
      el: 'select',
      props: { placeholder: '请选择租约状态', clearable: true },
    },
    enum: [
      { label: '签约待确认', value: 1 },
      { label: '已签约', value: 2 },
      { label: '已取消', value: 3 },
      { label: '已到期', value: 4 },
      { label: '退租待确认', value: 5 },
      { label: '已退租', value: 6 },
      { label: '续约待确认', value: 7 },
    ],
  },
  { prop: 'apartmentInfo.name', label: '签约公寓' },
  { prop: 'apartmentInfo.provinceName', label: '所处省份' },
  { prop: 'apartmentInfo.cityName', label: '所处城市' },
  { prop: 'apartmentInfo.districtName', label: '所处区域' },
  {
    prop: 'leaseStartDate',
    label: '租约周期',
    width: 200,
    render: ({ row }: { row: AgreementInfoInterface }) => {
      return row.leaseStartDate + ' ～ ' + row.leaseEndDate
    },
  },
  { prop: 'rent', label: '租金（元/月）' },
  { prop: 'deposit', label: '押金（元）' },
  {
    prop: 'paymentType.name',
    label: '支付方式',
  },
  { prop: 'leaseTerm.monthCount', label: '租期（月）' },
  {
    prop: 'sourceType',
    label: '租约来源',
    render: ({ row }: { row: AgreementInfoInterface }) => {
      const sourceLabel = getLabelByValue(AgreementSourceMap, row.sourceType)
      let tagType = 'info'
      if (row.sourceType === 3) { // 直接入住申请
        tagType = 'success'
      } else if (row.sourceType === 2) { // 续约
        tagType = 'warning'
      }
      return (
        <el-tag type={tagType}>
          {sourceLabel}
        </el-tag>
      )
    },
  },
  {
    prop: 'creatorType',
    label: '创建者类型',
    render: ({ row }: { row: AgreementInfoInterface }) => {
      const creatorLabel = getLabelByValue(CreatorTypeMap, row.creatorType)
      const tagType = row.creatorType === 1 ? 'primary' : 'success'
      return (
        <el-tag type={tagType}>
          {creatorLabel}
        </el-tag>
      )
    },
  },
  {
    prop: 'autoGenerated',
    label: '生成方式',
    render: ({ row }: { row: AgreementInfoInterface }) => {
      // 后端返回Integer类型：0-否，1-是
      return row.autoGenerated === 1 ? (
        <el-tag type="success">自动生成</el-tag>
      ) : (
        <el-tag type="info">手动创建</el-tag>
      )
    },
  },
  {
    prop: 'status',
    label: '租约状态',
    render: ({ row }: { row: AgreementInfoInterface }) => {
      switch (row.status) {
        case AgreementStatus.WAITING:
          return (
            <el-tag type="warning">
              {getLabelByValue(AgreementStatusMap, row.status)}
            </el-tag>
          )
        case AgreementStatus.RENEW_TO_BE_CONFIRMED:
          return (
            <el-tag type="warning">
              {getLabelByValue(AgreementStatusMap, row.status)}
            </el-tag>
          )
        case AgreementStatus.SIGNED:
          return (
            <el-tag type="success">
              {getLabelByValue(AgreementStatusMap, row.status)}
            </el-tag>
          )
        case AgreementStatus.TO_BE_CONFIRMED:
          return (
            <el-tag type="danger">
              {getLabelByValue(AgreementStatusMap, row.status)}
            </el-tag>
          )
        default:
          return (
            <el-tag type="info">
              {getLabelByValue(AgreementStatusMap, row.status)}
            </el-tag>
          )
      }
    },
  },
  { prop: 'operation', label: '操作', fixed: 'right', width: 320 },
]

// *查询参数
const initParam = reactive({})

//#region <省市区查询相关>
// 获取省份
async function getProvinceListHandle() {
  try {
    const { data } = await getProvinceList()
    areaInfo.provinceList = data
    proTable.value?.enumMap.set('provinceId', areaInfo.provinceList)
  } catch (error) {
    console.log(error)
  }
}
// 获取城市
async function getCityListHandle(provinceId: number) {
  try {
    const { data } = await getCityList(provinceId)
    areaInfo.cityList = data
    proTable.value?.enumMap.set('cityId', areaInfo.cityList)
  } catch (error) {
    console.log(error)
  }
}
// 获取区域
async function getDistrictListHandle(cityId: number) {
  try {
    const { data } = await getDistrictList(cityId)
    areaInfo.districtList = data
    proTable.value?.enumMap.set('districtId', areaInfo.districtList)
  } catch (error) {
    console.log(error)
  }
}
// 获取公寓
async function getApartmentListHandle(districtId: number) {
  try {
    const { data } = await getApartmentListByDistrictId(districtId)
    areaInfo.apartmentList = data
    proTable.value?.enumMap.set('apartmentId', areaInfo.apartmentList)
  } catch (error) {
    console.log(error)
  }
}
// 重置市数据
function resetCity() {
  areaInfo.cityId = ''
  areaInfo.cityList = []
  proTable.value?.enumMap.set('cityId', [])
  proTable.value!.searchParam.cityId = ''
}
// 重置区数据
function resetDistrict() {
  areaInfo.districtId = ''
  areaInfo.districtList = []
  proTable.value?.enumMap.set('districtId', [])
  proTable.value!.searchParam.districtId = ''
}
// 重置公寓数据
function resetApartment() {
  areaInfo.apartmentId = ''
  areaInfo.apartmentList = []
  proTable.value?.enumMap.set('apartmentId', [])
  proTable.value!.searchParam.apartmentId = ''
}
// 省份改变回调
const provinceChangeCallback = async () => {
  let provinceId = proTable.value!.searchParam.provinceId
  if (provinceId) {
    resetCity()
    resetDistrict()
    resetApartment()
    await getCityListHandle(provinceId)
  }
}
// 省份清除回调
const provinceClearCallback = () => {
  areaInfo.provinceId = ''
  proTable.value!.searchParam.provinceId = ''
  resetCity()
  resetDistrict()
  resetApartment()
}
// 城市改变回调
const cityChangeCallback = async () => {
  let cityId = proTable.value!.searchParam.cityId
  if (cityId) {
    resetDistrict()
    resetApartment()
    await getDistrictListHandle(cityId)
  }
}
// 城市清除回调
const cityClearCallback = () => {
  console.log('清空城市')
  areaInfo.cityId = ''
  proTable.value!.searchParam.cityId = ''
  resetDistrict()
  resetApartment()
}
// 区域改变回调
const districtChangeCallback = async () => {
  let districtId = proTable.value!.searchParam.districtId
  if (districtId) {
    resetApartment()
    await getApartmentListHandle(districtId)
  }
}
// 区域清除回调
const districtClearCallback = () => {
  console.log('清空区域')
  areaInfo.districtId = ''
  proTable.value!.searchParam.districtId = ''
  resetApartment()
}
// 公寓改变回调
const apartmentChangeCallback = async () => {
  console.log('公寓改变')
}
// 公寓清除回调
const apartmentClearCallback = () => {
  console.log('清空公寓')
  areaInfo.apartmentId = ''
  proTable.value!.searchParam.apartmentId = ''
}
//#endregion

// 处理返回的数据格式
const dataCallback = (data: any) => {
  return {
    list: data?.records,
    total: data?.total,
  }
}
// 查看
const editHandle = (row: AgreementInfoInterface) => {
  router.push({
    path: '/rentManagement/agreement/addOrEditAgreement',
    query: {
      id: row.id,
    },
  })
}
// 新增
const addHandle = () => {
  router.push({
    path: '/rentManagement/agreement/addOrEditAgreement',
  })
}
// 删除
const deleteHandle = async (row: AgreementInfoInterface) => {
  await useHandleData(
    deleteAgreementInfoById,
    row.id,
    `删除${row.name + row.apartmentInfo.name + row.roomInfo.roomNumber}房间`,
  )
  // 修改row
  proTable.value?.getTableList()
}
// 取消租约
const cancelLeaseHandle = async (row: AgreementInfoInterface) => {
  await useHandleData(
    updateAgreementStatusById,
    { id: row.id, status: AgreementStatus.CANCELLED },
    `取消租约`,
  )
  // 修改row
  proTable.value?.getTableList()
}
// 确认续约（同意续约）
const confirmLeaseHandle = async (row: AgreementInfoInterface) => {
  await useHandleData(
    updateAgreementStatusById,
    { id: row.id, status: AgreementStatus.SIGNED, approved: true },
    `同意续约`,
  )
  // 修改row
  proTable.value?.getTableList()
  // 刷新统计数据
  await loadStatistics()
}
// 拒绝续约
const rejectLeaseHandle = async (row: AgreementInfoInterface) => {
  await useHandleData(
    updateAgreementStatusById,
    { id: row.id, status: AgreementStatus.SIGNED, approved: false },
    `拒绝续约`,
  )
  // 修改row
  proTable.value?.getTableList()
  // 刷新统计数据
  await loadStatistics()
}
// 确认退租
const confirmThrowLeaseHandle = async (row: AgreementInfoInterface) => {
  await useHandleData(
    updateAgreementStatusById,
    { id: row.id, status: AgreementStatus.CONFIRMED },
    `确认退租`,
  )
  // 修改row
  proTable.value?.getTableList()
  // 刷新统计数据
  await loadStatistics()
}

// 计算属性：根据状态获取数量
const getStatusCount = (status: number) => {
  // 直接从后端返回的数据中获取对应状态的数量
  switch (status) {
    case AgreementStatus.SIGNED:
      return statistics.signed || 0
    case AgreementStatus.WAITING:
      return statistics.signing || 0
    case AgreementStatus.CANCELLED:
      return statistics.canceled || 0
    default:
      return 0
  }
}

// 计算属性：自动生成的租约数量
const autoGeneratedCount = computed(() => {
  return statistics.autoGenerated || 0
})

// 加载统计数据
const loadStatistics = async () => {
  try {
    const { data } = await getAgreementStatistics()
    Object.assign(statistics, data)
    
    // 将后端返回的简单数字字段转换为图表需要的数组格式
    statistics.statusStats = [
      { status: AgreementStatus.SIGNED, count: data.signed || 0, label: '已签约' },
      { status: AgreementStatus.WAITING, count: data.signing || 0, label: '签约待确认' },
      { status: AgreementStatus.CANCELLED, count: data.canceled || 0, label: '已取消' },
    ].filter(item => item.count > 0) // 只显示有数据的状态
    
    statistics.sourceStats = [
      { sourceType: 1, count: data.newLease || 0, label: '新签' },
      { sourceType: 2, count: data.renewLease || 0, label: '续约' },
      { sourceType: 3, count: data.directApplication || 0, label: '直接入住申请' },
    ].filter(item => item.count > 0) // 只显示有数据的来源
    
    // 更新图表
    await nextTick()
    initCharts()
  } catch (error) {
    console.error('加载统计数据失败:', error)
  }
}

// 刷新统计数据
const refreshStatistics = async () => {
  await loadStatistics()
  proTable.value?.getTableList()
}

// 初始化图表
const initCharts = () => {
  initStatusChart()
  initSourceChart()
}

// 初始化状态分布图表
const initStatusChart = () => {
  if (!statusChartRef.value) return
  
  if (statusChart) {
    statusChart.dispose()
  }
  
  statusChart = echarts.init(statusChartRef.value)
  
  const option = {
    tooltip: {
      trigger: 'item',
      formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    legend: {
      orient: 'vertical',
      left: 'left'
    },
    series: [
      {
        name: '租约状态',
        type: 'pie',
        radius: '50%',
        data: statistics.statusStats.map(item => ({
          value: item.count,
          name: item.label
        })),
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
    ]
  }
  
  statusChart.setOption(option)
}

// 初始化来源分布图表
const initSourceChart = () => {
  if (!sourceChartRef.value) return
  
  if (sourceChart) {
    sourceChart.dispose()
  }
  
  sourceChart = echarts.init(sourceChartRef.value)
  
  const option = {
    tooltip: {
      trigger: 'item',
      formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    legend: {
      orient: 'vertical',
      left: 'left'
    },
    series: [
      {
        name: '租约来源',
        type: 'pie',
        radius: '50%',
        data: statistics.sourceStats.map(item => ({
          value: item.count,
          name: item.label
        })),
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
    ]
  }
  
  sourceChart.setOption(option)
}

// 切换视图（普通视图 vs 所有租约视图）
const switchToAllView = () => {
  showAllLeases.value = !showAllLeases.value
  // 切换API接口
  if (showAllLeases.value) {
    // 使用getAllAgreements接口
    proTable.value!.requestApi = getAllAgreements
  } else {
    // 使用getAgreementInfoList接口
    proTable.value!.requestApi = getAgreementInfoList
  }
  // 刷新表格数据
  proTable.value?.getTableList()
}

// 查看即将到期的租约
const viewExpiringLeases = async () => {
  try {
    const { data } = await getExpiringLeases()
    if (data && data.length > 0) {
      ElMessageBox.alert(
        `共有 ${data.length} 个租约即将到期，请及时处理！`,
        '即将到期租约提醒',
        {
          confirmButtonText: '确定',
          type: 'warning',
        }
      )
    } else {
      ElMessage.success('暂无即将到期的租约')
    }
  } catch (error) {
    console.error('获取即将到期租约失败:', error)
    ElMessage.error('获取即将到期租约失败')
  }
}

// 发送到期提醒
const sendReminderHandle = async (row: AgreementInfoInterface) => {
  try {
    await sendExpirationReminder(row.id)
    ElMessage.success('到期提醒发送成功')
  } catch (error) {
    console.error('发送到期提醒失败:', error)
    ElMessage.error('发送到期提醒失败')
  }
}

// 终止租约（退租）
const terminateLeaseHandle = async (row: AgreementInfoInterface) => {
  try {
    const { value: reason } = await ElMessageBox.prompt(
      '请输入终止租约的原因',
      '终止租约',
      {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        inputPattern: /.+/,
        inputErrorMessage: '请输入终止原因',
      }
    )
    
    await terminateLease(row.id, reason)
    ElMessage.success('租约终止成功')
    proTable.value?.getTableList()
    await loadStatistics()
  } catch (error) {
    if (error !== 'cancel') {
      console.error('终止租约失败:', error)
      ElMessage.error('终止租约失败')
    }
  }
}

// 修改并重新发送租约
const updateAndResendHandle = async (row: AgreementInfoInterface) => {
  try {
    // 这里应该打开一个编辑对话框，暂时跳转到编辑页面
    router.push({
      path: '/rentManagement/agreement/addOrEditAgreement',
      query: {
        id: row.id,
        mode: 'resend'
      },
    })
  } catch (error) {
    console.error('修改租约失败:', error)
    ElMessage.error('修改租约失败')
  }
}

onMounted(() => {
  // 获取省份
  getProvinceListHandle()
  // 加载统计数据
  loadStatistics()
})
</script>

<style scoped>
.statistics-card {
  border-radius: 8px;
  overflow: hidden;
}

.card-content {
  display: flex;
  align-items: center;
  padding: 10px;
}

.card-icon {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 15px;
  font-size: 24px;
  color: white;
}

.card-icon.total {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.card-icon.signed {
  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
}

.card-icon.waiting {
  background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
}

.card-icon.auto {
  background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%);
}

.card-info {
  flex: 1;
}

.card-title {
  font-size: 14px;
  color: #666;
  margin-bottom: 5px;
}

.card-value {
  font-size: 28px;
  font-weight: bold;
  color: #333;
}

.statistics-card:hover {
  transform: translateY(-2px);
  transition: transform 0.3s ease;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}
</style>
