package com.atguigu.lease.web.admin.vo.agreement;

import com.atguigu.lease.model.enums.LeaseSourceType;
import com.atguigu.lease.model.enums.LeaseStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(description = "租约查询实体")
public class AgreementQueryVo {

    @Schema(description = "公寓所处省份id")
    private Long provinceId;

    @Schema(description = "公寓所处城市id")
    private Long cityId;

    @Schema(description = "公寓所处区域id")
    private Long districtId;

    @Schema(description = "公寓id")
    private Long apartmentId;

    @Schema(description = "房间号")
    private String roomNumber;

    @Schema(description = "用户姓名")
    private String name;

    @Schema(description = "用户手机号码")
    private String phone;

    @Schema(description = "创建者类型：1-官方，2-房东")
    private Integer creatorType;

    @Schema(description = "租约来源类型：1-新签，2-续约，3-直接入住申请")
    private Integer sourceType;

    @Schema(description = "租约状态：1-签约待确认，2-已签约，3-已取消，4-已到期，5-退租待确认，6-已退租，7-续约待确认")
    private Integer status;

    @Schema(description = "生成方式：0-手动创建，1-自动生成")
    private Integer autoGenerated;

}
