<template>
  <div class="lease-detail">
    <!-- 导航栏 -->
    <van-nav-bar 
      title="租约详情" 
      left-arrow 
      @click-left="handleGoBack"
      fixed
      placeholder
    >
      <template #right>
        <van-icon name="edit" @click="goToEdit" />
      </template>
    </van-nav-bar>

    <!-- 页面内容 -->
    <div v-if="leaseDetail" class="content">
      <!-- 租约状态卡片 -->
      <div class="status-card">
        <div class="status-header">
          <van-tag 
            :color="getLeaseStatusColor(leaseDetail.status)"
            plain
            size="large"
          >
            {{ getLeaseStatusName(leaseDetail.status) }}
          </van-tag>
          <div class="status-meta">
            <span class="source-type">{{ getLeaseSourceTypeName(leaseDetail.sourceType) }}</span>
            <span v-if="leaseDetail.autoGenerated" class="auto-tag">自动生成</span>
            <span v-else class="manual-tag">手动创建</span>
          </div>
        </div>
        
        <!-- 到期提醒 -->
        <div v-if="isExpiringSoon" class="expiring-notice">
          <van-notice-bar
            color="#ff9500"
            background="#fff7cc"
            left-icon="warning-o"
          >
            租约将在{{ leaseDetail.remainingDays }}天后到期，请及时处理
          </van-notice-bar>
        </div>
        
        <!-- 租约基本状态信息 -->
        <div class="status-info">
          <div class="status-item">
            <span class="status-label">剩余天数</span>
            <span class="status-value" :class="{ 'expiring': isExpiringSoon }">
              {{ leaseDetail.remainingDays }}天
            </span>
          </div>
          <div class="status-item">
            <span class="status-label">租约来源</span>
            <span class="status-value">{{ getLeaseSourceTypeName(leaseDetail.sourceType) }}</span>
          </div>
          <div class="status-item">
            <span class="status-label">创建方式</span>
            <span class="status-value">
              {{ leaseDetail.autoGenerated ? '系统自动生成' : '手动创建' }}
            </span>
          </div>
        </div>
      </div>

      <!-- 房源信息 -->
      <div class="info-card">
        <div class="card-title">
          <van-icon name="home-o" />
          房源信息
        </div>
        <div class="info-content">
          <div class="info-row">
            <span class="info-label">公寓名称</span>
            <span class="info-value">{{ leaseDetail.apartmentInfo.name }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">房间号</span>
            <span class="info-value">{{ leaseDetail.roomInfo.roomNumber }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">地址</span>
            <span class="info-value">
              {{ leaseDetail.apartmentInfo.provinceName }}{{ leaseDetail.apartmentInfo.cityName }}{{ leaseDetail.apartmentInfo.districtName }}
            </span>
          </div>
        </div>
      </div>

      <!-- 租客信息 -->
      <div class="info-card">
        <div class="card-title">
          <van-icon name="contact" />
          租客信息
        </div>
        <div class="info-content">
          <div class="info-row">
            <span class="info-label">姓名</span>
            <span class="info-value">{{ leaseDetail.name }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">手机号</span>
            <span class="info-value">
              {{ leaseDetail.phone }}
              <van-icon name="phone-o" @click="callTenant" class="action-icon" />
            </span>
          </div>
          <div class="info-row">
            <span class="info-label">身份证号</span>
            <span class="info-value">{{ maskIdCard(leaseDetail.identificationNumber) }}</span>
          </div>
        </div>
      </div>

      <!-- 租赁条款 -->
      <div class="info-card">
        <div class="card-title">
          <van-icon name="description" />
          租赁条款
        </div>
        <div class="info-content">
          <div class="info-row">
            <span class="info-label">租金</span>
            <span class="info-value rent">¥{{ leaseDetail.rent }}/月</span>
          </div>
          <div class="info-row">
            <span class="info-label">押金</span>
            <span class="info-value">¥{{ leaseDetail.deposit }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">租期</span>
            <span class="info-value">{{ leaseDetail.leaseTerm.monthCount }}{{ leaseDetail.leaseTerm.unit }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">支付方式</span>
            <span class="info-value">{{ leaseDetail.paymentType.name }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">开始时间</span>
            <span class="info-value">{{ formatDate(leaseDetail.leaseStartDate) }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">结束时间</span>
            <span class="info-value">{{ formatDate(leaseDetail.leaseEndDate) }}</span>
          </div>
          <div v-if="leaseDetail.remainingDays > 0" class="info-row">
            <span class="info-label">剩余天数</span>
            <span class="info-value" :class="{ 'expiring': leaseDetail.remainingDays <= 30 }">
              {{ leaseDetail.remainingDays }}天
            </span>
          </div>
        </div>
      </div>

      <!-- 附加信息 -->
      <div v-if="leaseDetail.additionalInfo" class="info-card">
        <div class="card-title">
          <van-icon name="notes-o" />
          附加信息
        </div>
        <div class="info-content">
          <div class="additional-info">
            {{ leaseDetail.additionalInfo }}
          </div>
        </div>
      </div>

      <!-- 创建信息 -->
      <div class="info-card">
        <div class="card-title">
          <van-icon name="clock-o" />
          创建信息
        </div>
        <div class="info-content">
          <div class="info-row">
            <span class="info-label">创建时间</span>
            <span class="info-value">{{ formatDateTime(leaseDetail.createTime) }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">更新时间</span>
            <span class="info-value">{{ formatDateTime(leaseDetail.updateTime) }}</span>
          </div>
          <div v-if="leaseDetail.applicationId" class="info-row clickable-row" @click="goToApplication">
            <span class="info-label">关联申请</span>
            <span class="info-value">
              申请ID: {{ leaseDetail.applicationId }}
              <van-icon name="arrow" class="action-icon" />
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- 底部操作栏 -->
    <div v-if="leaseDetail" class="action-bar">
      <van-button 
        v-for="action in availableActions" 
        :key="action.key"
        :type="action.type"
        :color="action.color"
        size="large"
        @click="handleAction(action.key)"
        class="action-button"
      >
        {{ action.label }}
      </van-button>
    </div>

    <!-- 加载状态 -->
    <van-loading v-if="loading" class="loading-overlay" vertical>
      加载中...
    </van-loading>

    <!-- 状态变更确认对话框 -->
    <van-dialog
      v-model:show="showStatusDialog"
      :title="statusDialogTitle"
      :message="statusDialogMessage"
      show-cancel-button
      @confirm="executeStatusChange"
    />

    <!-- 到期提醒对话框 -->
    <van-dialog
      v-model:show="showReminderDialog"
      title="发送到期提醒"
      message="确定要向租客发送到期提醒吗？"
      show-cancel-button
      @confirm="sendReminder"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { showToast, showConfirmDialog } from 'vant';
import { NavigationHelper } from '@/utils/navigationHelper';
import { useUserStore } from '@/store/modules/user';
import {
  getLandlordLeaseDetail,
  updateLeaseStatus,
  sendExpirationReminder,
  resendLease,
  getLeaseStatusName,
  getLeaseStatusColor,
  getLeaseSourceTypeName,
  LeaseStatus,
  type LandlordLeaseDetailVo
} from '@/api/landlord/lease';

const router = useRouter();
const route = useRoute();
const userStore = useUserStore();

// 响应式数据
const loading = ref(false);
const leaseDetail = ref<LandlordLeaseDetailVo | null>(null);
const showStatusDialog = ref(false);
const showReminderDialog = ref(false);
const pendingStatus = ref<LeaseStatus | null>(null);
const pendingApproved = ref<boolean | undefined>(undefined);

// 计算是否即将到期（30天内）
const isExpiringSoon = computed(() => {
  return leaseDetail.value ? leaseDetail.value.remainingDays <= 30 : false;
});

// 获取租约ID
const leaseId = computed(() => Number(route.params.id));

// 状态变更对话框内容
const statusDialogTitle = computed(() => {
  if (!pendingStatus.value) return '';
  return `确认${getLeaseStatusName(pendingStatus.value)}`;
});

const statusDialogMessage = computed(() => {
  if (!pendingStatus.value) return '';
  const statusName = getLeaseStatusName(pendingStatus.value);
  return `确定要将租约状态变更为"${statusName}"吗？此操作不可撤销。`;
});

// 可用操作按钮
const availableActions = computed(() => {
  if (!leaseDetail.value) return [];
  
  const actions = [];
  const status = leaseDetail.value.status;
  
  switch (status) {
    case LeaseStatus.SIGNING:
      // 签约待确认：房东可以取消租约，但不能确认（由租客确认）
      actions.push(
        { key: 'cancel', label: '取消租约', type: 'danger', color: '#fa5151' }
      );
      break;
      
    case LeaseStatus.SIGNED:
      // 已签约：房东可以发起退租、续约，发送提醒
      actions.push(
        { key: 'withdraw', label: '发起退租', type: 'warning', color: '#ff9500' },
        { key: 'renew', label: '发起续约', type: 'primary', color: '#1989fa' }
      );
      // 如果即将到期，显示发送提醒按钮
      if (leaseDetail.value.isExpiringSoon || leaseDetail.value.remainingDays <= 30) {
        actions.push(
          { key: 'reminder', label: '发送到期提醒', type: 'default', color: '#969799' }
        );
      }
      break;
      
    case LeaseStatus.CANCELED:
      // 已取消：房东可以重发租约
      actions.push(
        { key: 'resend', label: '重发租约', type: 'primary', color: '#1989fa' }
      );
      break;
      
    case LeaseStatus.WITHDRAWING:
      // 退租待确认：房东可以确认或拒绝退租
      actions.push(
        { key: 'confirmWithdraw', label: '确认退租', type: 'primary', color: '#07c160' },
        { key: 'rejectWithdraw', label: '拒绝退租', type: 'danger', color: '#fa5151' }
      );
      break;
      
    case LeaseStatus.RENEWING:
      // 续约待确认：房东可以确认或拒绝续约
      actions.push(
        { key: 'confirmRenew', label: '确认续约', type: 'primary', color: '#07c160' },
        { key: 'rejectRenew', label: '拒绝续约', type: 'danger', color: '#fa5151' }
      );
      break;
      
    case LeaseStatus.EXPIRED:
      // 已到期：房东可以重新签约
      actions.push(
        { key: 'renew', label: '重新签约', type: 'primary', color: '#1989fa' }
      );
      break;
      
    case LeaseStatus.WITHDRAWN:
      // 已退租：无可用操作
      break;
  }
  
  return actions;
});

// 加载租约详情
const loadLeaseDetail = async () => {
  try {
    loading.value = true;
    
    console.log('🔍 开始加载租约详情 - leaseId:', leaseId.value);
    const response = await getLandlordLeaseDetail(leaseId.value);
    leaseDetail.value = response.data;
    console.log('✅ 租约详情加载成功:', response.data);
  } catch (error) {
    console.error('加载租约详情失败:', error);
    showToast('加载失败，请重试');
  } finally {
    loading.value = false;
  }
};

// 处理操作按钮点击
const handleAction = (actionKey: string) => {
  switch (actionKey) {
    case 'confirm':
      confirmStatusChange(LeaseStatus.SIGNED);
      break;
    case 'cancel':
      confirmStatusChange(LeaseStatus.CANCELED);
      break;
    case 'withdraw':
      confirmStatusChange(LeaseStatus.WITHDRAWING);
      break;
    case 'confirmWithdraw':
      confirmStatusChange(LeaseStatus.WITHDRAWN);
      break;
    case 'rejectWithdraw':
      confirmStatusChange(LeaseStatus.SIGNED);
      break;
    case 'renew':
      confirmStatusChange(LeaseStatus.RENEWING);
      break;
    case 'confirmRenew':
      confirmStatusChange(LeaseStatus.SIGNED, true); // 同意续约，延长日期
      break;
    case 'rejectRenew':
      confirmStatusChange(LeaseStatus.SIGNED, false); // 拒绝续约，不延长日期
      break;
    case 'reminder':
      showReminderDialog.value = true;
      break;
    case 'resend':
      handleResendLease();
      break;
  }
};

// 确认状态变更
const confirmStatusChange = (status: LeaseStatus, approved?: boolean) => {
  pendingStatus.value = status;
  pendingApproved.value = approved;
  showStatusDialog.value = true;
};

// 执行状态变更
const executeStatusChange = async () => {
  if (!pendingStatus.value || !leaseDetail.value) return;
  
  try {
    console.log('🔄 开始更新租约状态 - leaseId:', leaseDetail.value.id, 'status:', pendingStatus.value, 'approved:', pendingApproved.value);
    await updateLeaseStatus(leaseDetail.value.id, pendingStatus.value, undefined, pendingApproved.value);
    showToast('状态更新成功');
    leaseDetail.value.status = pendingStatus.value;
    console.log('✅ 租约状态更新成功');
    
    // 重新加载租约详情以获取最新的日期信息
    await loadLeaseDetail();
  } catch (error) {
    console.error('状态更新失败:', error);
    showToast('状态更新失败，请重试');
  } finally {
    pendingStatus.value = null;
    pendingApproved.value = undefined;
  }
};

// 发送到期提醒
const sendReminder = async () => {
  if (!leaseDetail.value) return;
  
  try {
    console.log('📧 开始发送到期提醒 - leaseId:', leaseDetail.value.id);
    await sendExpirationReminder(leaseDetail.value.id);
    showToast('提醒发送成功');
    console.log('✅ 到期提醒发送成功');
  } catch (error) {
    console.error('发送提醒失败:', error);
    showToast('发送提醒失败，请重试');
  }
};

// 重发租约
const handleResendLease = async () => {
  if (!leaseDetail.value) return;
  
  try {
    await showConfirmDialog({
      title: '重发租约',
      message: `确定要重新发送租约给租客"${leaseDetail.value.name}"吗？您可以在编辑界面中修改租约信息。`,
      confirmButtonText: '进入编辑',
      cancelButtonText: '取消'
    });
    
    console.log('🔄 跳转到租约编辑页面 - leaseId:', leaseDetail.value.id);
    
    // 跳转到租约编辑页面，传递原租约ID和重发标识
    router.push({
      name: 'LandlordLeaseForm',
      params: { id: 'new' },
      query: { 
        resendFrom: leaseDetail.value.id.toString(),
        mode: 'resend'
      }
    });
    
  } catch (error: any) {
    if (error !== 'cancel') {
      console.error('跳转编辑页面失败:', error);
    }
  }
};

// 工具方法
const formatDate = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString();
};

const formatDateTime = (dateStr: string): string => {
  return new Date(dateStr).toLocaleString();
};

const maskIdCard = (idCard: string): string => {
  if (!idCard || idCard.length < 8) return idCard;
  return idCard.substring(0, 4) + '****' + idCard.substring(idCard.length - 4);
};

// 导航方法
const goToEdit = () => {
  if (!leaseDetail.value) return;
  router.push({
    name: 'LandlordLeaseForm',
    params: { id: leaseDetail.value.id }
  });
};

const goToApplication = () => {
  if (!leaseDetail.value?.applicationId) return;
  router.push({
    name: 'LandlordApplicationDetail',
    params: { id: leaseDetail.value.applicationId }
  });
};

const callTenant = () => {
  if (!leaseDetail.value?.phone) return;
  window.location.href = `tel:${leaseDetail.value.phone}`;
};

// 返回按钮处理
const handleGoBack = () => {
  console.log('🧭 租约详情页面返回按钮被点击');
  NavigationHelper.smartGoBack(router);
};

// 组件挂载时加载数据
onMounted(() => {
  loadLeaseDetail();
});
</script>

<style scoped>
.lease-detail {
  min-height: 100vh;
  background-color: #f7f8fa;
  padding-bottom: 80px;
}

.content {
  padding: 16px;
}

/* 状态卡片 */
.status-card {
  background: white;
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.status-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.status-meta {
  display: flex;
  gap: 8px;
  font-size: 12px;
}

.source-type {
  color: #646566;
}

.auto-tag {
  color: #1989fa;
}

.manual-tag {
  color: #646566;
}

.status-info {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid #ebedf0;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
}

.status-item {
  text-align: center;
}

.status-label {
  display: block;
  font-size: 12px;
  color: #969799;
  margin-bottom: 4px;
}

.status-value {
  display: block;
  font-size: 14px;
  color: #323233;
  font-weight: 500;
}

.status-value.expiring {
  color: #ff9500;
  font-weight: bold;
}

.expiring-notice {
  margin-top: 12px;
}

/* 信息卡片 */
.info-card {
  background: white;
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.card-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 16px;
  font-weight: bold;
  color: #323233;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid #ebedf0;
}

.card-title .van-icon {
  color: #1989fa;
}

.info-content {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.info-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.info-label {
  font-size: 14px;
  color: #646566;
  flex-shrink: 0;
  width: 80px;
}

.info-value {
  font-size: 14px;
  color: #323233;
  text-align: right;
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
}

.info-value.rent {
  color: #07c160;
  font-weight: bold;
  font-size: 16px;
}

.info-value.expiring {
  color: #ff9500;
  font-weight: bold;
}

.action-icon {
  color: #1989fa;
  cursor: pointer;
  font-size: 16px;
}

.additional-info {
  font-size: 14px;
  color: #323233;
  line-height: 1.6;
  background: #f7f8fa;
  padding: 12px;
  border-radius: 8px;
}

/* 底部操作栏 */
.action-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: white;
  padding: 12px 16px;
  border-top: 1px solid #ebedf0;
  display: flex;
  gap: 12px;
  z-index: 100;
}

.action-button {
  flex: 1;
}

/* 加载状态 */
.loading-overlay {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1000;
}

/* 可点击行样式 */
.clickable-row {
  cursor: pointer;
  transition: background-color 0.2s ease;
  border-radius: 6px;
  padding: 8px;
  margin: -8px;
}

.clickable-row:hover {
  background-color: #f7f8fa;
}

.clickable-row:active {
  background-color: #ebedf0;
  transform: scale(0.98);
}

/* 响应式适配 */
@media (max-width: 375px) {
  .info-label {
    width: 70px;
    font-size: 13px;
  }
  
  .info-value {
    font-size: 13px;
  }
  
  .action-bar {
    padding: 8px 12px;
  }
}
</style>