<template>
  <div class="lease-list">
    <!-- 导航栏 -->
    <van-nav-bar 
      title="租约列表" 
      left-arrow 
      @click-left="handleGoBack"
      fixed
      placeholder
    />

    <!-- 搜索栏 -->
    <div class="search-section">
      <van-search
        v-model="searchKeyword"
        placeholder="搜索租客姓名、手机号、房间号"
        @search="onSearch"
        @clear="onClear"
        show-action
      >
        <template #action>
          <div @click="showFilter = true">筛选</div>
        </template>
      </van-search>
    </div>

    <!-- 筛选条件显示 -->
    <div v-if="hasActiveFilters" class="filter-tags">
      <van-tag 
        v-if="queryParams.status" 
        closeable 
        @close="clearFilter('status')"
        color="#1989fa"
      >
        {{ getLeaseStatusName(queryParams.status) }}
      </van-tag>
      <van-tag 
        v-if="queryParams.sourceType" 
        closeable 
        @close="clearFilter('sourceType')"
        color="#07c160"
      >
        {{ getLeaseSourceTypeName(queryParams.sourceType) }}
      </van-tag>
      <van-tag 
        v-if="queryParams.apartmentId" 
        closeable 
        @close="clearFilter('apartmentId')"
        color="#ff9500"
      >
        {{ selectedApartmentName }}
      </van-tag>
      <van-tag 
        v-if="queryParams.autoGenerated !== undefined" 
        closeable 
        @close="clearFilter('autoGenerated')"
        color="#9c26b0"
      >
        {{ queryParams.autoGenerated ? '自动生成' : '手动创建' }}
      </van-tag>
    </div>

    <!-- 租约列表 -->
    <van-pull-refresh v-model="refreshing" @refresh="onRefresh">
      <van-list
        v-model:loading="loading"
        :finished="finished"
        finished-text="没有更多了"
        @load="onLoad"
      >
        <div class="lease-items">
          <div 
            v-for="lease in leaseList" 
            :key="lease.id"
            class="lease-card"
            @click="goToDetail(lease.id)"
          >
            <!-- 租约状态标签 -->
            <div class="lease-status-badge">
              <van-tag 
                :color="getLeaseStatusColor(lease.status)"
                plain
                size="medium"
              >
                {{ getLeaseStatusName(lease.status) }}
              </van-tag>
            </div>

            <!-- 租约基本信息 -->
            <div class="lease-header">
              <div class="lease-title">
                {{ lease.apartmentInfo.name }} - {{ lease.roomInfo.roomNumber }}
              </div>
              <div class="lease-location">
                {{ lease.apartmentInfo.provinceName }}{{ lease.apartmentInfo.cityName }}{{ lease.apartmentInfo.districtName }}
              </div>
            </div>

            <!-- 租客信息 -->
            <div class="lease-tenant">
              <div class="tenant-info">
                <van-icon name="contact" size="16" />
                <span class="tenant-name">{{ lease.name }}</span>
                <span class="tenant-phone">{{ lease.phone }}</span>
              </div>
            </div>

            <!-- 租约详情 -->
            <div class="lease-details">
              <div class="detail-row">
                <div class="detail-item">
                  <span class="detail-label">租金</span>
                  <span class="detail-value rent">¥{{ lease.rent }}/月</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">押金</span>
                  <span class="detail-value">¥{{ lease.deposit }}</span>
                </div>
              </div>
              <div class="detail-row">
                <div class="detail-item">
                  <span class="detail-label">租期</span>
                  <span class="detail-value">{{ lease.leaseTerm.monthCount }}{{ lease.leaseTerm.unit }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">支付方式</span>
                  <span class="detail-value">{{ lease.paymentType.name }}</span>
                </div>
              </div>
            </div>

            <!-- 租约时间 -->
            <div class="lease-time">
              <div class="time-item">
                <span class="time-label">开始时间</span>
                <span class="time-value">{{ formatDate(lease.leaseStartDate) }}</span>
              </div>
              <div class="time-item">
                <span class="time-label">结束时间</span>
                <span class="time-value">{{ formatDate(lease.leaseEndDate) }}</span>
              </div>
              <div class="time-item" v-if="lease.remainingDays > 0">
                <span class="time-label">剩余天数</span>
                <span class="time-value" :class="{ 'expiring': lease.remainingDays <= 30 }">
                  {{ lease.remainingDays }}天
                </span>
              </div>
            </div>

            <!-- 租约来源和类型 -->
            <div class="lease-meta">
              <van-tag size="small" plain>
                {{ getLeaseSourceTypeName(lease.sourceType) }}
              </van-tag>
              <van-tag size="small" plain v-if="lease.autoGenerated">
                自动生成
              </van-tag>
              <span class="create-time">{{ formatDateTime(lease.createTime) }}</span>
            </div>
          </div>
        </div>

        <!-- 空状态 -->
        <van-empty 
          v-if="!loading && leaseList.length === 0" 
          description="暂无租约数据"
          image="search"
        />
      </van-list>
    </van-pull-refresh>

    <!-- 筛选弹窗 -->
    <van-popup v-model:show="showFilter" position="bottom" :style="{ height: '60%' }">
      <div class="filter-popup">
        <div class="filter-header">
          <div class="filter-title">筛选条件</div>
          <div class="filter-actions">
            <van-button size="small" @click="resetFilters">重置</van-button>
            <van-button size="small" type="primary" @click="applyFilters">确定</van-button>
          </div>
        </div>

        <div class="filter-content">
          <!-- 租约状态筛选 -->
          <div class="filter-section">
            <div class="filter-section-title">租约状态</div>
            <div class="filter-options">
              <van-tag 
                v-for="status in statusOptions" 
                :key="status.value"
                :type="tempFilters.status === status.value ? 'primary' : 'default'"
                @click="selectStatus(status.value)"
                class="filter-tag"
              >
                {{ status.label }}
              </van-tag>
            </div>
          </div>

          <!-- 租约来源筛选 -->
          <div class="filter-section">
            <div class="filter-section-title">租约来源</div>
            <div class="filter-options">
              <van-tag 
                v-for="source in sourceOptions" 
                :key="source.value"
                :type="tempFilters.sourceType === source.value ? 'primary' : 'default'"
                @click="selectSourceType(source.value)"
                class="filter-tag"
              >
                {{ source.label }}
              </van-tag>
            </div>
          </div>

          <!-- 公寓筛选 -->
          <div class="filter-section">
            <div class="filter-section-title">所属公寓</div>
            <van-field
              v-model="selectedApartmentName"
              placeholder="选择公寓"
              readonly
              is-link
              @click="showApartmentPicker = true"
            />
          </div>

          <!-- 创建方式筛选 -->
          <div class="filter-section">
            <div class="filter-section-title">创建方式</div>
            <div class="filter-options">
              <van-tag 
                :type="tempFilters.autoGenerated === true ? 'primary' : 'default'"
                @click="selectAutoGenerated(true)"
                class="filter-tag"
              >
                自动生成
              </van-tag>
              <van-tag 
                :type="tempFilters.autoGenerated === false ? 'primary' : 'default'"
                @click="selectAutoGenerated(false)"
                class="filter-tag"
              >
                手动创建
              </van-tag>
            </div>
          </div>
        </div>
      </div>
    </van-popup>

    <!-- 公寓选择器 -->
    <van-popup v-model:show="showApartmentPicker" position="bottom">
      <van-picker
        :columns="apartmentOptions"
        @confirm="onApartmentConfirm"
        @cancel="showApartmentPicker = false"
      />
    </van-popup>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useUserStore } from '@/store/modules/user';
import { NavigationHelper } from '@/utils/navigationHelper';
import {
  getLandlordLeaseList,
  getLeaseStatusName,
  getLeaseStatusColor,
  getLeaseSourceTypeName,
  LeaseStatus,
  LeaseSourceType,
  type LandlordLeaseVo,
  type LandlordLeaseQueryVo
} from '@/api/landlord/lease';

const router = useRouter();
const route = useRoute();
const userStore = useUserStore();

// 响应式数据
const loading = ref(false);
const refreshing = ref(false);
const finished = ref(false);
const showFilter = ref(false);
const showApartmentPicker = ref(false);
const searchKeyword = ref('');
const leaseList = ref<LandlordLeaseVo[]>([]);
const selectedApartmentName = ref('');

// 分页参数
const pagination = reactive({
  current: 1,
  size: 10,
  total: 0
});

// 查询参数
const queryParams = reactive<LandlordLeaseQueryVo>({
  keyword: '',
  status: undefined,
  sourceType: undefined,
  apartmentId: undefined,
  autoGenerated: undefined
});

// 临时筛选条件（用于弹窗）
const tempFilters = reactive<LandlordLeaseQueryVo>({});

// 筛选选项
const statusOptions = [
  { label: '签约待确认', value: LeaseStatus.SIGNING },
  { label: '已签约', value: LeaseStatus.SIGNED },
  { label: '已取消', value: LeaseStatus.CANCELED },
  { label: '已到期', value: LeaseStatus.EXPIRED },
  { label: '退租待确认', value: LeaseStatus.WITHDRAWING },
  { label: '已退租', value: LeaseStatus.WITHDRAWN },
  { label: '续约待确认', value: LeaseStatus.RENEWING }
];

const sourceOptions = [
  { label: '新签', value: LeaseSourceType.NEW_LEASE },
  { label: '续约', value: LeaseSourceType.RENEW_LEASE },
  { label: '直接入住申请', value: LeaseSourceType.DIRECT_APPLICATION }
];

const apartmentOptions = ref<Array<{ text: string; value: number }>>([]);

// 计算属性
const hasActiveFilters = computed(() => {
  return queryParams.status !== undefined ||
         queryParams.sourceType !== undefined ||
         queryParams.apartmentId !== undefined ||
         queryParams.autoGenerated !== undefined;
});

// 初始化路由参数
const initFromRoute = () => {
  const query = route.query;
  if (query.status) {
    queryParams.status = Number(query.status) as LeaseStatus;
  }
  if (query.sourceType) {
    queryParams.sourceType = Number(query.sourceType) as LeaseSourceType;
  }
  if (query.apartmentId) {
    queryParams.apartmentId = Number(query.apartmentId);
  }
  if (query.autoGenerated !== undefined) {
    queryParams.autoGenerated = query.autoGenerated === 'true';
  }
  if (query.keyword) {
    searchKeyword.value = String(query.keyword);
    queryParams.keyword = String(query.keyword);
  }
};

// 加载租约列表
const loadLeaseList = async (isRefresh = false) => {
  try {
    if (isRefresh) {
      pagination.current = 1;
      finished.value = false;
    }

    loading.value = true;
    
    console.log('🔍 开始加载租约列表 - current:', pagination.current, 'size:', pagination.size);
    
    const response = await getLandlordLeaseList(
      pagination.current,
      pagination.size,
      queryParams
    );

    const { records, total } = response.data;
    
    if (isRefresh) {
      leaseList.value = records;
    } else {
      leaseList.value.push(...records);
    }
    
    pagination.total = total;
    pagination.current++;
    
    // 判断是否加载完毕
    if (leaseList.value.length >= total) {
      finished.value = true;
    }
    
    console.log('✅ 租约列表加载成功，共', records.length, '条记录');
  } catch (error) {
    console.error('加载租约列表失败:', error);
  } finally {
    loading.value = false;
    refreshing.value = false;
  }
};

// 下拉刷新
const onRefresh = () => {
  loadLeaseList(true);
};

// 上拉加载
const onLoad = () => {
  if (!finished.value) {
    loadLeaseList();
  }
};

// 搜索
const onSearch = (value: string) => {
  queryParams.keyword = value;
  loadLeaseList(true);
};

// 清空搜索
const onClear = () => {
  queryParams.keyword = '';
  loadLeaseList(true);
};

// 筛选相关方法
const selectStatus = (status: LeaseStatus) => {
  tempFilters.status = tempFilters.status === status ? undefined : status;
};

const selectSourceType = (sourceType: LeaseSourceType) => {
  tempFilters.sourceType = tempFilters.sourceType === sourceType ? undefined : sourceType;
};

const selectAutoGenerated = (autoGenerated: boolean) => {
  tempFilters.autoGenerated = tempFilters.autoGenerated === autoGenerated ? undefined : autoGenerated;
};

const clearFilter = (key: keyof LandlordLeaseQueryVo) => {
  queryParams[key] = undefined;
  if (key === 'apartmentId') {
    selectedApartmentName.value = '';
  }
  loadLeaseList(true);
};

const resetFilters = () => {
  Object.keys(tempFilters).forEach(key => {
    tempFilters[key as keyof LandlordLeaseQueryVo] = undefined;
  });
  selectedApartmentName.value = '';
};

const applyFilters = () => {
  Object.assign(queryParams, tempFilters);
  showFilter.value = false;
  loadLeaseList(true);
};

// 公寓选择
const onApartmentConfirm = ({ selectedValues, selectedOptions }: any) => {
  tempFilters.apartmentId = selectedValues[0];
  selectedApartmentName.value = selectedOptions[0]?.text || '';
  showApartmentPicker.value = false;
};

// 格式化日期
const formatDate = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString();
};

const formatDateTime = (dateStr: string): string => {
  return new Date(dateStr).toLocaleString();
};

// 导航到详情页
const goToDetail = (leaseId: number) => {
  router.push({
    name: 'LandlordLeaseDetail',
    params: { id: leaseId }
  });
};

// 返回按钮处理
const handleGoBack = () => {
  console.log('🧭 租约列表页面返回按钮被点击');
  NavigationHelper.smartGoBack(router);
};

// 组件挂载时初始化
onMounted(() => {
  initFromRoute();
  loadLeaseList(true);
  // TODO: 加载公寓选项
  // loadApartmentOptions();
});
</script>

<style scoped>
.lease-list {
  min-height: 100vh;
  background-color: #f7f8fa;
}

/* 搜索区域 */
.search-section {
  padding: 12px 16px;
  background: white;
  border-bottom: 1px solid #ebedf0;
}

/* 筛选标签 */
.filter-tags {
  padding: 8px 16px;
  background: white;
  border-bottom: 1px solid #ebedf0;
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

/* 租约列表 */
.lease-items {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.lease-card {
  background: white;
  border-radius: 12px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.2s;
  position: relative;
}

.lease-card:active {
  transform: scale(0.98);
}

.lease-status-badge {
  position: absolute;
  top: 12px;
  right: 12px;
}

/* 租约头部 */
.lease-header {
  margin-bottom: 12px;
  padding-right: 80px;
}

.lease-title {
  font-size: 16px;
  font-weight: bold;
  color: #323233;
  margin-bottom: 4px;
}

.lease-location {
  font-size: 12px;
  color: #969799;
}

/* 租客信息 */
.lease-tenant {
  margin-bottom: 12px;
}

.tenant-info {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #646566;
}

.tenant-name {
  font-weight: bold;
  color: #323233;
}

.tenant-phone {
  color: #1989fa;
}

/* 租约详情 */
.lease-details {
  margin-bottom: 12px;
}

.detail-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
}

.detail-row:last-child {
  margin-bottom: 0;
}

.detail-item {
  display: flex;
  flex-direction: column;
  flex: 1;
}

.detail-label {
  font-size: 12px;
  color: #969799;
  margin-bottom: 2px;
}

.detail-value {
  font-size: 14px;
  color: #323233;
  font-weight: bold;
}

.detail-value.rent {
  color: #07c160;
}

/* 租约时间 */
.lease-time {
  margin-bottom: 12px;
  display: flex;
  justify-content: space-between;
  font-size: 12px;
}

.time-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.time-label {
  color: #969799;
  margin-bottom: 2px;
}

.time-value {
  color: #323233;
  font-weight: bold;
}

.time-value.expiring {
  color: #ff9500;
}

/* 租约元信息 */
.lease-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.create-time {
  color: #969799;
  margin-left: auto;
}

/* 筛选弹窗 */
.filter-popup {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.filter-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  border-bottom: 1px solid #ebedf0;
}

.filter-title {
  font-size: 16px;
  font-weight: bold;
  color: #323233;
}

.filter-actions {
  display: flex;
  gap: 8px;
}

.filter-content {
  flex: 1;
  padding: 16px;
  overflow-y: auto;
}

.filter-section {
  margin-bottom: 24px;
}

.filter-section-title {
  font-size: 14px;
  font-weight: bold;
  color: #323233;
  margin-bottom: 12px;
}

.filter-options {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.filter-tag {
  cursor: pointer;
}
</style>