package com.atguigu.lease.web.app.vo.landlord;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

/**
 * 房东租约统计数据VO
 * 用于房东查看租约统计信息
 */
@Data
@Schema(description = "房东租约统计数据")
public class LandlordLeaseStatisticsVo {

    @Schema(description = "租约总数")
    private Long total;

    @Schema(description = "签约待确认数量")
    private Long signing;

    @Schema(description = "已签约数量")
    private Long signed;

    @Schema(description = "已取消数量")
    private Long canceled;

    @Schema(description = "已到期数量")
    private Long expired;

    @Schema(description = "退租待确认数量")
    private Long withdrawing;

    @Schema(description = "已退租数量")
    private Long withdrawn;

    @Schema(description = "续约待确认数量")
    private Long renewing;

    @Schema(description = "即将到期数量（30天内）")
    private Long expiring;

    @Schema(description = "总租金收入")
    private BigDecimal totalRent;

    @Schema(description = "总押金收入")
    private BigDecimal totalDeposit;

    @Schema(description = "新签租约数量")
    private Long newLease;

    @Schema(description = "续约租约数量")
    private Long renewLease;

    @Schema(description = "直接入住申请租约数量")
    private Long directApplication;

    @Schema(description = "自动生成租约数量")
    private Long autoGenerated;

    @Schema(description = "手动创建租约数量")
    private Long manualCreated;

    @Schema(description = "状态统计列表")
    private List<StatusStatVo> statusStats;

    @Schema(description = "来源统计列表")
    private List<SourceStatVo> sourceStats;
}