package com.atguigu.lease.web.app.vo.landlord;

import com.atguigu.lease.model.entity.*;
import com.atguigu.lease.model.enums.LeaseSourceType;
import com.atguigu.lease.model.enums.LeaseStatus;
import com.atguigu.lease.web.app.vo.attr.AttrValueVo;
import com.atguigu.lease.web.app.vo.fee.FeeValueVo;
import com.atguigu.lease.web.app.vo.graph.GraphVo;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * 房东租约详情VO
 * 用于房东查看租约的完整详细信息
 */
@Data
@Schema(description = "房东租约详情信息")
public class LandlordLeaseDetailVo {

    @Schema(description = "租约ID")
    private Long id;

    @Schema(description = "承租人手机号码")
    private String phone;

    @Schema(description = "承租人姓名")
    private String name;

    @Schema(description = "承租人身份证号码")
    private String identificationNumber;

    @Schema(description = "签约公寓信息")
    private ApartmentInfo apartmentInfo;

    @Schema(description = "签约房间信息")
    private RoomInfo roomInfo;

    @Schema(description = "租约开始日期")
    private Date leaseStartDate;

    @Schema(description = "租约结束日期")
    private Date leaseEndDate;

    @Schema(description = "租期信息")
    private LeaseTerm leaseTerm;

    @Schema(description = "租金（元/月）")
    private BigDecimal rent;

    @Schema(description = "押金（元）")
    private BigDecimal deposit;

    @Schema(description = "支付方式信息")
    private PaymentType paymentType;

    @Schema(description = "租约状态")
    private LeaseStatus status;

    @Schema(description = "租约来源")
    private LeaseSourceType sourceType;

    @Schema(description = "创建者类型：1-官方，2-房东")
    private Integer creatorType;

    @Schema(description = "创建者ID")
    private Long creatorId;

    @Schema(description = "关联的直接入住申请ID")
    private Long applicationId;

    @Schema(description = "是否自动生成：0-否，1-是")
    private Integer autoGenerated;

    @Schema(description = "备注信息")
    private String additionalInfo;

    @Schema(description = "创建时间")
    private Date createTime;

    @Schema(description = "更新时间")
    private Date updateTime;

    @Schema(description = "剩余天数")
    private Integer remainingDays;

    @Schema(description = "是否即将到期（30天内）")
    private Boolean isExpiringSoon;

    @Schema(description = "房间配套设施列表")
    private List<FacilityInfo> facilityInfoList;

    @Schema(description = "房间标签列表")
    private List<LabelInfo> labelInfoList;

    @Schema(description = "房间属性列表")
    private List<AttrValueVo> attrValueVoList;

    @Schema(description = "房间杂费列表")
    private List<FeeValueVo> feeValueVoList;

    @Schema(description = "房间图片列表")
    private List<GraphVo> graphVoList;

    @Schema(description = "公寓图片列表")
    private List<GraphVo> apartmentGraphVoList;

    @Schema(description = "可执行的操作列表")
    private List<String> availableActions;
}