package com.atguigu.lease.web.app.vo.landlord;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * 房东租约查询条件VO
 * 用于房东查询租约时的筛选条件
 */
@Data
@Schema(description = "房东租约查询条件")
public class LandlordLeaseQueryVo {

    @Schema(description = "关键词搜索（租客姓名、手机号、房间号）")
    private String keyword;

    @Schema(description = "租约状态：1-签约待确认，2-已签约，3-已取消，4-已到期，5-退租待确认，6-已退租，7-续约待确认")
    private Integer status;

    @Schema(description = "租约来源类型：1-新签，2-续约，3-直接入住申请")
    private Integer sourceType;

    @Schema(description = "公寓ID")
    private Long apartmentId;

    @Schema(description = "生成方式：0-手动创建，1-自动生成")
    private Integer autoGenerated;
}