import http from '@/utils/http'
import {
  AgreementInfoInterface,
  AgreementInfoListQueryInterface,
  AgreementInterface,
  AppointmentInfoInterface,
  AppointmentInfoListQueryInterface,
  RoomInfoInterface,
} from '@/api/rentManagement/types'
import { PageRes } from '@/api/types'
import { AgreementStatus, AppointmentStatus } from '@/enums/constEnums'
//#region <预约看房>
/**
 * @description 分页查询预约信息
 * @param params
 */
export function getAppointmentInfoList(
  params: AppointmentInfoListQueryInterface,
) {
  return http.get<PageRes<AppointmentInfoInterface[]>>(
    `/admin/appointment/page`,
    {
      current: params.pageNum,
      size: params.pageSize,
      provinceId: params.provinceId,
      cityId: params.cityId,
      districtId: params.districtId,
      apartmentId: params.apartmentId,
      name: params.name,
      phone: params.phone,
      guideType: params.guideType,
      sortField: params.sortField,
      sortOrder: params.sortOrder,
    },
  )
}
/**
 * @description 根据id更新预约状态
 * @param id
 * @param status
 */
export function updateAppointmentStatusById(
  id: number | string,
  status: AppointmentStatus,
) {
  return http.post(
    `/admin/appointment/updateStatusById?id=${id}&status=${status}`,
  )
}
//#endregion
//#region <租赁管理>
/**
 * @description 分页查询租约信息
 * @param params
 */
export function getAgreementInfoList(params: AgreementInfoListQueryInterface) {
  return http.get<PageRes<AgreementInfoInterface[]>>(`/admin/agreement/page`, {
    current: params.pageNum,
    size: params.pageSize,
    provinceId: params.provinceId,
    cityId: params.cityId,
    districtId: params.districtId,
    apartmentId: params.apartmentId,
    roomNumber: params.roomNumber,
    name: params.name,
    phone: params.phone,
    creatorType: params.creatorType,
    sourceType: params.sourceType,
    status: params.status,
    autoGenerated: params.autoGenerated,
  })
}
/**
 * @description 根据公寓id查询房间列表
 * @param apartmentId
 */
export function getRoomListByApartmentId(apartmentId: number | string) {
  return http.get<RoomInfoInterface[]>(
    `/admin/room/listBasicByApartmentId?id=${apartmentId}`,
  )
}
/**
 * @description 根据id查询租约信息
 * @param id
 */
export function getAgreementInfoById(id: number | string) {
  return http.get<AgreementInfoInterface>(`/admin/agreement?id=${id}`)
}
/**
 * @description 保存或修改租约信息
 * @param data
 */
export function saveOrUpdateAgreementInfo(data: AgreementInterface) {
  return http.post(`/admin/agreement/saveOrUpdate`, data)
}
/**
 * @description 根据id删除租约信息
 * @param id
 */
export function deleteAgreementInfoById(id: number | string) {
  return http.delete(`/admin/agreement/removeById?id=${id}`)
}
/**
 * @description 根据id更新租约状态
 * @param id
 * @param status
 * @param approved 是否同意（用于续约场景）
 */
export function updateAgreementStatusById({
  id,
  status,
  approved,
}: {
  id: number | string
  status: AgreementStatus
  approved?: boolean
}) {
  const approvedParam = approved !== undefined ? `&approved=${approved}` : '';
  return http.post(
    `/admin/agreement/updateStatusById?id=${id}&status=${status}${approvedParam}`,
  )
}

/**
 * @description 获取租约统计数据
 */
export function getAgreementStatistics() {
  return http.get<{
    totalCount: number
    statusStats: { status: number; count: number; label: string }[]
    sourceStats: { sourceType: number; count: number; label: string }[]
    creatorStats: { creatorType: number; count: number; label: string }[]
    monthlyStats: { month: string; count: number }[]
  }>(`/admin/agreement/statistics`)
}

/**
 * @description 获取所有租约列表（官方后台统一查看）
 * @param params 查询参数
 */
export function getAllAgreements(params: AgreementInfoListQueryInterface) {
  return http.get<PageRes<AgreementInfoInterface[]>>(`/admin/agreement/all`, {
    current: params.pageNum,
    size: params.pageSize,
    provinceId: params.provinceId,
    cityId: params.cityId,
    districtId: params.districtId,
    apartmentId: params.apartmentId,
    roomNumber: params.roomNumber,
    name: params.name,
    phone: params.phone,
    creatorType: params.creatorType,
    sourceType: params.sourceType,
    status: params.status,
    autoGenerated: params.autoGenerated,
  })
}

/**
 * @description 更新租约状态（增强版）
 * @param leaseId 租约ID
 * @param newStatus 新状态
 * @param reason 变更原因
 */
export function updateLeaseStatus(leaseId: number | string, newStatus: string, reason?: string) {
  return http.post(`/admin/agreement/updateStatus`, null, {
    params: {
      leaseId,
      newStatus,
      reason,
    },
  })
}

/**
 * @description 批量更新租约状态
 * @param leaseIds 租约ID列表
 * @param newStatus 新状态
 * @param reason 变更原因
 */
export function batchUpdateLeaseStatus(leaseIds: number[], newStatus: string, reason?: string) {
  return http.post(`/admin/agreement/batchUpdateStatus`, leaseIds, {
    params: {
      newStatus,
      reason,
    },
  })
}

/**
 * @description 获取即将到期的租约
 */
export function getExpiringLeases() {
  return http.get<AgreementInfoInterface[]>(`/admin/agreement/expiring`)
}

/**
 * @description 修改租约并重新发送
 * @param leaseId 租约ID
 * @param updatedLease 更新的租约信息
 */
export function updateAndResendLease(leaseId: number | string, updatedLease: AgreementInterface) {
  return http.post(`/admin/agreement/updateAndResend`, updatedLease, {
    params: { leaseId },
  })
}

/**
 * @description 终止租约
 * @param leaseId 租约ID
 * @param terminationReason 终止原因
 */
export function terminateLease(leaseId: number | string, terminationReason: string) {
  return http.post(`/admin/agreement/terminate`, null, {
    params: {
      leaseId,
      terminationReason,
    },
  })
}

/**
 * @description 发送租约到期提醒
 * @param leaseId 租约ID
 */
export function sendExpirationReminder(leaseId: number | string) {
  return http.post(`/admin/agreement/sendExpirationReminder`, null, {
    params: { leaseId },
  })
}

/**
 * @description 获取租约状态变更历史
 * @param leaseId 租约ID
 */
export function getLeaseStatusHistory(leaseId: number | string) {
  return http.get(`/admin/agreement/statusHistory`, {
    params: { leaseId },
  })
}
//#endregion
