/**
 * 房东租约管理API接口
 */

import http from '@/utils/http';

// 租约状态枚举
export enum LeaseStatus {
  SIGNING = 1,      // 签约待确认
  SIGNED = 2,       // 已签约
  CANCELED = 3,     // 已取消
  EXPIRED = 4,      // 已到期
  WITHDRAWING = 5,  // 退租待确认
  WITHDRAWN = 6,    // 已退租
  RENEWING = 7      // 续约待确认
}

// 租约来源枚举
export enum LeaseSourceType {
  NEW_LEASE = 1,           // 新签
  RENEW_LEASE = 2,         // 续约
  DIRECT_APPLICATION = 3   // 直接入住申请
}

// 租约查询参数
export interface LandlordLeaseQueryVo {
  keyword?: string;        // 关键词搜索（租客姓名、手机号、房间号）
  status?: LeaseStatus;    // 租约状态
  sourceType?: LeaseSourceType; // 租约来源
  apartmentId?: number;    // 公寓ID
  autoGenerated?: boolean; // 是否自动生成
}

// 租约基本信息
export interface LandlordLeaseVo {
  id: number;
  phone: string;
  name: string;
  identificationNumber: string;
  leaseStartDate: string;
  leaseEndDate: string;
  rent: number;
  deposit: number;
  status: LeaseStatus;
  sourceType: LeaseSourceType;
  creatorType: number;
  creatorId: number;
  applicationId?: number;
  autoGenerated: boolean;
  additionalInfo?: string;
  createTime: string;
  updateTime: string;
  remainingDays: number;
  
  // 关联信息
  apartmentInfo: {
    id: number;
    name: string;
    districtId: number;
    districtName: string;
    cityId: number;
    cityName: string;
    provinceId: number;
    provinceName: string;
  };
  
  roomInfo: {
    id: number;
    roomNumber: string;
  };
  
  paymentType: {
    id: number;
    name: string;
    payMonthCount: number;
  };
  
  leaseTerm: {
    id: number;
    monthCount: number;
    unit: string;
  };
}

// 租约详情信息
export interface LandlordLeaseDetailVo extends LandlordLeaseVo {
  isExpiringSoon: boolean; // 是否即将到期
}

// 租约统计信息（包含状态和来源统计）
export interface LandlordLeaseStatisticsVo {
  total: number;           // 总数
  signing: number;         // 签约待确认
  signed: number;          // 已签约
  canceled: number;        // 已取消
  expired: number;         // 已到期
  withdrawing: number;     // 退租待确认
  withdrawn: number;       // 已退租
  renewing: number;        // 续约待确认
  expiring: number;        // 即将到期（30天内）
  totalRent: number;       // 总租金收入
  totalDeposit: number;    // 总押金收入
  newLease: number;        // 新签租约
  renewLease: number;      // 续约租约
  directApplication: number; // 直接入住申请
  autoGenerated: number;   // 自动生成
  manualCreated: number;   // 手动创建
  statusStats?: StatusStatVo[]; // 状态统计
  sourceStats?: SourceStatVo[]; // 来源统计
}

// 状态统计
export interface StatusStatVo {
  status: LeaseStatus;
  statusName: string;
  count: number;
  percentage?: number;
}

// 来源统计
export interface SourceStatVo {
  sourceType: LeaseSourceType | null;
  sourceTypeName: string;
  count: number;
  percentage?: number;
}

// 租约创建参数
export interface LandlordLeaseCreateVo {
  phone: string;
  name: string;
  identificationNumber: string;
  leaseStartDate: string;
  leaseEndDate: string;
  rent: number;
  deposit: number;
  apartmentId: number;
  roomId: number;
  paymentTypeId: number;
  leaseTermId: number;
  additionalInfo?: string;
}

// 分页结果
export interface PageResult<T> {
  records: T[];
  total: number;
  size: number;
  current: number;
  pages: number;
}

/**
 * 获取房东租约列表（分页）
 */
export const getLandlordLeaseList = (
  current: number = 1,
  size: number = 10,
  queryVo?: LandlordLeaseQueryVo
) => {
  const params: any = {
    current,
    size
  };
  
  // 添加查询条件
  if (queryVo) {
    if (queryVo.keyword) params.keyword = queryVo.keyword;
    if (queryVo.status) params.status = queryVo.status;
    if (queryVo.sourceType) params.sourceType = queryVo.sourceType;
    if (queryVo.apartmentId) params.apartmentId = queryVo.apartmentId;
    if (queryVo.autoGenerated !== undefined) params.autoGenerated = queryVo.autoGenerated;
  }
  
  return http.get<PageResult<LandlordLeaseVo>>('/app/landlord/leases/list', params);
};

/**
 * 获取租约详情
 */
export const getLandlordLeaseDetail = (leaseId: number) => {
  return http.get<LandlordLeaseDetailVo>(`/app/landlord/leases/detail-full/${leaseId}`);
};

/**
 * 更新租约状态
 */
export const updateLeaseStatus = (leaseId: number, status: LeaseStatus, reason?: string, approved?: boolean) => {
  const params: any = { status };
  if (reason) params.reason = reason;
  if (approved !== undefined) params.approved = approved;
  
  return http.post(`/app/landlord/leases/status/${leaseId}`, null, {
    params
  });
};

/**
 * 获取租约统计数据
 */
export const getLandlordLeaseStatistics = () => {
  return http.get<LandlordLeaseStatisticsVo>('/app/landlord/leases/statistics');
};

/**
 * 获取租约状态统计
 */
export const getLandlordLeaseStatusStats = () => {
  return http.get<LandlordLeaseStatisticsVo>('/app/landlord/leases/statistics').then(res => ({
    data: res.data.statusStats || []
  }));
};

/**
 * 获取租约来源统计
 */
export const getLandlordLeaseSourceStats = () => {
  return http.get<LandlordLeaseStatisticsVo>('/app/landlord/leases/statistics').then(res => ({
    data: res.data.sourceStats || []
  }));
};

/**
 * 获取即将到期的租约
 */
export const getExpiringLeases = (days: number = 30) => {
  return http.get<LandlordLeaseVo[]>('/app/landlord/leases/expiring', {
    days
  });
};

/**
 * 创建租约
 */
export const createLease = (data: LandlordLeaseCreateVo) => {
  return http.post('/app/landlord/leases/create', data);
};

/**
 * 更新租约
 */
export const updateLease = (leaseId: number, data: Partial<LandlordLeaseCreateVo>) => {
  return http.put(`/app/landlord/leases/update/${leaseId}`, data);
};

/**
 * 发送到期提醒
 */
export const sendExpirationReminder = (leaseId: number) => {
  return http.post(`/app/landlord/leases/reminder/${leaseId}`);
};

/**
 * 重发租约
 */
export const resendLease = (leaseId: number, data?: LandlordLeaseCreateVo) => {
  if (data) {
    // 带数据的重发租约（用于修改后重发）
    return http.post<number>(`/app/landlord/leases/resend/${leaseId}`, data);
  } else {
    // 简单重发租约（不修改数据）
    return http.post<number>(`/app/landlord/leases/resend/${leaseId}`);
  }
};

/**
 * 获取租约状态名称
 */
export const getLeaseStatusName = (status: LeaseStatus): string => {
  const statusMap = {
    [LeaseStatus.SIGNING]: '签约待确认',
    [LeaseStatus.SIGNED]: '已签约',
    [LeaseStatus.CANCELED]: '已取消',
    [LeaseStatus.EXPIRED]: '已到期',
    [LeaseStatus.WITHDRAWING]: '退租待确认',
    [LeaseStatus.WITHDRAWN]: '已退租',
    [LeaseStatus.RENEWING]: '续约待确认'
  };
  return statusMap[status] || '未知状态';
};

/**
 * 获取租约来源名称
 */
export const getLeaseSourceTypeName = (sourceType: LeaseSourceType): string => {
  const sourceMap = {
    [LeaseSourceType.NEW_LEASE]: '新签',
    [LeaseSourceType.RENEW_LEASE]: '续约',
    [LeaseSourceType.DIRECT_APPLICATION]: '直接入住申请'
  };
  return sourceMap[sourceType] || '未知来源';
};

/**
 * 获取租约状态颜色
 */
export const getLeaseStatusColor = (status: LeaseStatus): string => {
  const colorMap = {
    [LeaseStatus.SIGNING]: '#ff9500',      // 橙色 - 待确认
    [LeaseStatus.SIGNED]: '#07c160',       // 绿色 - 已签约
    [LeaseStatus.CANCELED]: '#fa5151',     // 红色 - 已取消
    [LeaseStatus.EXPIRED]: '#c8c9cc',      // 灰色 - 已到期
    [LeaseStatus.WITHDRAWING]: '#ff9500',  // 橙色 - 退租待确认
    [LeaseStatus.WITHDRAWN]: '#c8c9cc',    // 灰色 - 已退租
    [LeaseStatus.RENEWING]: '#1989fa'      // 蓝色 - 续约待确认
  };
  return colorMap[status] || '#c8c9cc';
};