<template>
  <div 
    class="lease-card"
    :class="{ 'expiring': isExpiring }"
    @click="$emit('click', lease)"
  >
    <!-- 租约状态标签 -->
    <div class="lease-status-badge">
      <van-tag 
        :color="getLeaseStatusColor(lease.status)"
        plain
        size="medium"
      >
        {{ getLeaseStatusName(lease.status) }}
      </van-tag>
    </div>

    <!-- 租约基本信息 -->
    <div class="lease-header">
      <div class="lease-title">
        {{ lease.apartmentInfo.name }} - {{ lease.roomInfo.roomNumber }}
      </div>
      <div class="lease-location">
        {{ lease.apartmentInfo.provinceName }}{{ lease.apartmentInfo.cityName }}{{ lease.apartmentInfo.districtName }}
      </div>
    </div>

    <!-- 租客信息 -->
    <div class="lease-tenant">
      <div class="tenant-info">
        <van-icon name="contact" size="16" />
        <span class="tenant-name">{{ lease.name }}</span>
        <span class="tenant-phone">{{ lease.phone }}</span>
      </div>
    </div>

    <!-- 租约详情 -->
    <div class="lease-details">
      <div class="detail-row">
        <div class="detail-item">
          <span class="detail-label">租金</span>
          <span class="detail-value rent">¥{{ lease.rent }}/月</span>
        </div>
        <div class="detail-item">
          <span class="detail-label">押金</span>
          <span class="detail-value">¥{{ lease.deposit }}</span>
        </div>
      </div>
      <div class="detail-row">
        <div class="detail-item">
          <span class="detail-label">租期</span>
          <span class="detail-value">{{ lease.leaseTerm.monthCount }}{{ lease.leaseTerm.unit }}</span>
        </div>
        <div class="detail-item">
          <span class="detail-label">支付方式</span>
          <span class="detail-value">{{ lease.paymentType.name }}</span>
        </div>
      </div>
    </div>

    <!-- 租约时间 -->
    <div class="lease-time">
      <div class="time-item">
        <span class="time-label">开始时间</span>
        <span class="time-value">{{ formatDate(lease.leaseStartDate) }}</span>
      </div>
      <div class="time-item">
        <span class="time-label">结束时间</span>
        <span class="time-value">{{ formatDate(lease.leaseEndDate) }}</span>
      </div>
      <div class="time-item" v-if="lease.remainingDays > 0">
        <span class="time-label">剩余天数</span>
        <span class="time-value" :class="{ 'expiring': lease.remainingDays <= 30 }">
          {{ lease.remainingDays }}天
        </span>
      </div>
    </div>

    <!-- 租约来源和类型 -->
    <div class="lease-meta">
      <van-tag size="small" plain>
        {{ getLeaseSourceTypeName(lease.sourceType) }}
      </van-tag>
      <van-tag size="small" plain v-if="lease.autoGenerated">
        自动生成
      </van-tag>
      <span class="create-time">{{ formatDateTime(lease.createTime) }}</span>
    </div>

    <!-- 即将到期提醒 -->
    <div v-if="isExpiring" class="expiring-notice">
      <van-notice-bar
        color="#ff9500"
        background="#fff7cc"
        left-icon="warning-o"
        :scrollable="false"
      >
        {{ lease.remainingDays }}天后到期
      </van-notice-bar>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  getLeaseStatusName,
  getLeaseStatusColor,
  getLeaseSourceTypeName,
  type LandlordLeaseVo
} from '@/api/landlord/lease';

// Props
interface Props {
  lease: LandlordLeaseVo;
  showExpiring?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showExpiring: true
});

// Emits
defineEmits<{
  click: [lease: LandlordLeaseVo];
}>();

// 计算属性
const isExpiring = computed(() => {
  return props.showExpiring && props.lease.remainingDays > 0 && props.lease.remainingDays <= 30;
});

// 格式化日期
const formatDate = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString();
};

const formatDateTime = (dateStr: string): string => {
  return new Date(dateStr).toLocaleString();
};
</script>

<style scoped>
.lease-card {
  background: white;
  border-radius: 12px;
  padding: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
  position: relative;
  margin-bottom: 12px;
}

.lease-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.lease-card:active {
  transform: scale(0.98);
}

.lease-card.expiring {
  border-left: 4px solid #ff9500;
  background: linear-gradient(90deg, #fff7e6 0%, white 10%);
}

.lease-status-badge {
  position: absolute;
  top: 12px;
  right: 12px;
}

/* 租约头部 */
.lease-header {
  margin-bottom: 12px;
  padding-right: 80px;
}

.lease-title {
  font-size: 16px;
  font-weight: bold;
  color: #323233;
  margin-bottom: 4px;
}

.lease-location {
  font-size: 12px;
  color: #969799;
}

/* 租客信息 */
.lease-tenant {
  margin-bottom: 12px;
}

.tenant-info {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #646566;
}

.tenant-name {
  font-weight: bold;
  color: #323233;
}

.tenant-phone {
  color: #1989fa;
}

/* 租约详情 */
.lease-details {
  margin-bottom: 12px;
}

.detail-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
}

.detail-row:last-child {
  margin-bottom: 0;
}

.detail-item {
  display: flex;
  flex-direction: column;
  flex: 1;
}

.detail-label {
  font-size: 12px;
  color: #969799;
  margin-bottom: 2px;
}

.detail-value {
  font-size: 14px;
  color: #323233;
  font-weight: bold;
}

.detail-value.rent {
  color: #07c160;
}

/* 租约时间 */
.lease-time {
  margin-bottom: 12px;
  display: flex;
  justify-content: space-between;
  font-size: 12px;
}

.time-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.time-label {
  color: #969799;
  margin-bottom: 2px;
}

.time-value {
  color: #323233;
  font-weight: bold;
}

.time-value.expiring {
  color: #ff9500;
}

/* 租约元信息 */
.lease-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  margin-bottom: 8px;
}

.create-time {
  color: #969799;
  margin-left: auto;
}

/* 即将到期提醒 */
.expiring-notice {
  margin-top: 8px;
}

/* 响应式适配 */
@media (max-width: 375px) {
  .lease-card {
    padding: 12px;
  }
  
  .lease-header {
    padding-right: 70px;
  }
  
  .lease-title {
    font-size: 15px;
  }
  
  .lease-time {
    font-size: 11px;
  }
  
  .detail-value {
    font-size: 13px;
  }
}
</style>